export const challengeDifficulties = ["Alle", "Enkel", "Middels", "Utfordrende"] as const;
export type ChallengeDifficulty = (typeof challengeDifficulties)[number];

export type ChallengeHint = {
  label: string;
  title: string;
  body: string;
  code?: string;
};

export type ChallengeCheck = {
  label: string;
  codeIncludes?: string[];
  outputIncludes?: string[];
};

export type PythonChallenge = {
  id: string;
  difficulty: Exclude<ChallengeDifficulty, "Alle">;
  title: string;
  subject: string;
  estimatedMinutes: number;
  teaser: string;
  mission: string;
  whyItMatters: string;
  concepts: string[];
  beforeQuestions: string[];
  successCriteria: string[];
  testCases: { change: string; expect: string }[];
  hints: ChallengeHint[];
  scaffold: string;
  solutionCode: string;
  solutionWalkthrough: string[];
  reflection: string[];
  extension: string;
  shortcut?: { title: string; body: string; code: string };
  checks: ChallengeCheck[];
};

export const pythonChallenges: PythonChallenge[] = [
  {
    id: "sum-variables",
    difficulty: "Enkel",
    title: "Lag en forståelig sum",
    subject: "Variabler og utskrift",
    estimatedMinutes: 10,
    teaser: "La Python legge sammen to verdier og svare med en hel setning.",
    mission: "Lag variablene pris og frakt. Regn ut totalprisen, lagre svaret i en ny variabel og skriv: «Totalprisen er 648 kr.»",
    whyItMatters: "Nesten alle programmer tar imot verdier, bearbeider dem og viser et resultat. Her øver du på hele denne kjeden i liten skala.",
    concepts: ["variabler", "+", "print", "f-tekst"],
    beforeQuestions: ["Hvilke to verdier må Python kjenne?", "Hva bør variabelen som lagrer svaret hete?", "Hvilken del av utskriften er tekst, og hvilken del er en verdi?"],
    successCriteria: ["pris og frakt er lagret i hver sin variabel", "summen regnes ut med variabelnavn", "svaret inneholder både forklarende tekst og kr"],
    testCases: [{ change: "pris = 599 og frakt = 49", expect: "Totalprisen er 648 kr." }, { change: "pris = 80 og frakt = 20", expect: "Totalprisen er 100 kr." }],
    hints: [
      { label: "Lite dytt", title: "Start med navnelapper", body: "Lag først én variabel for hver verdi. Les en tildeling fra høyre: Tallet lagres under navnet til venstre." },
      { label: "Byggekloss", title: "En ny variabel kan lagre regnestykket", body: "Python kan hente verdiene gjennom navnene og lagre summen under et tredje navn.", code: "total = pris + frakt" },
      { label: "Plan", title: "Tre tydelige deler", body: "Programmet trenger først inndata, så beregning, så utskrift. La det gjerne være en tom linje mellom delene." },
      { label: "Nesten der", title: "Sett verdien inn i teksten", body: "En f foran teksten gjør at det i krøllparentesene byttes ut med verdien.", code: "print(f\"Totalprisen er {total} kr.\")" },
    ],
    scaffold: "pris = 599\nfrakt = 49\n\n# Lag variabelen total her\n\n# Skriv en forklarende setning her",
    solutionCode: "pris = 599\nfrakt = 49\n\ntotal = pris + frakt\n\nprint(f\"Totalprisen er {total} kr.\")",
    solutionWalkthrough: ["Python lagrer først de to verdiene.", "Høyresiden pris + frakt regnes ut før svaret lagres i total.", "F-teksten bytter {total} ut med 648."],
    reflection: ["Hvorfor er total = pris + frakt lettere å endre enn total = 599 + 49?", "Hva skjer hvis frakt får verdien 0?"],
    extension: "Legg til variabelen rabatt = 50 og trekk rabatten fra totalen før svaret skrives ut.",
    checks: [{ label: "Programmet regner med variabelnavn", codeIncludes: ["pris", "frakt", "+"] }, { label: "Resultatet viser totalpris og 648", outputIncludes: ["total", "648"] }],
  },
  {
    id: "discount",
    difficulty: "Enkel",
    title: "Regn ut en rabatt",
    subject: "Prosent og vekstfaktor",
    estimatedMinutes: 15,
    teaser: "Gjør 25 % rabatt om til en pris kunden faktisk skal betale.",
    mission: "En vare koster 800 kr og har 25 % rabatt. Lag et program som regner ut ny pris og skriver et forståelig svar uten unødvendige desimaler.",
    whyItMatters: "Programmering tvinger oss til å forklare prosentregningen presist: Hva er hele prisen, hva fjernes, og hva blir igjen?",
    concepts: ["desimaltall", "prosent", "parentes", "f-tekst"],
    beforeQuestions: ["Hva er 25 % skrevet som desimaltall?", "Hvis 25 % fjernes, hvor mange prosent beholdes?", "Hvorfor kan hele prisen representeres med tallet 1?"],
    successCriteria: ["25 % er skrevet som 0.25", "programmet regner ut delen som beholdes", "svaret viser 600 kr uten .0"],
    testCases: [{ change: "pris = 800 og rabatt = 0.25", expect: "600 kr" }, { change: "pris = 500 og rabatt = 0.10", expect: "450 kr" }],
    hints: [
      { label: "Lite dytt", title: "Fra prosent til desimaltall", body: "25 % betyr 25 av 100. I Python skrives det 0.25 med punktum." },
      { label: "Byggekloss", title: "Finn delen som er igjen", body: "1 betyr hele den gamle prisen, altså 100 %. Når rabatten trekkes fra 1, står delen kunden skal betale igjen.", code: "1 - rabatt" },
      { label: "Plan", title: "Pris ganger delen som beholdes", body: "Regn først ut parentesen. Med rabatt 0.25 blir den 0.75, som er det samme som 75 %." },
      { label: "Nesten der", title: "Vis kroner uten desimaler", body: "Formatkoden :.0f viser tallet med null desimaler.", code: "print(f\"Den nye prisen er {ny_pris:.0f} kr.\")" },
    ],
    scaffold: "pris = 800\nrabatt = 0.25\n\n# Regn ut ny_pris\n\n# Skriv svaret med en forklarende tekst",
    solutionCode: "pris = 800\nrabatt = 0.25\n\nny_pris = pris * (1 - rabatt)\n\nprint(f\"Den nye prisen er {ny_pris:.0f} kr.\")",
    solutionWalkthrough: ["1 representerer 100 % av den gamle prisen.", "1 - 0.25 blir 0.75, altså 75 %.", "800 * 0.75 blir 600.", ":.0f endrer bare hvordan tallet vises."],
    reflection: ["Hvorfor blir det feil å skrive pris * rabatt hvis vi vil finne den nye prisen?", "Hvordan ville du regnet ut selve rabattbeløpet?"],
    extension: "Skriv både «Du sparer 200 kr» og «Den nye prisen er 600 kr».",
    checks: [{ label: "Koden bruker delen som beholdes", codeIncludes: ["1 - rabatt"] }, { label: "Resultatet viser ny pris", outputIncludes: ["600", "kr"] }],
  },
  {
    id: "even-odd",
    difficulty: "Enkel",
    title: "Er tallet partall?",
    subject: "Vilkår og divisjonsrest",
    estimatedMinutes: 15,
    teaser: "La programmet avgjøre om et tall er partall eller oddetall.",
    mission: "Lag variabelen tall. Programmet skal skrive enten «14 er et partall» eller «14 er et oddetall», avhengig av verdien.",
    whyItMatters: "Her gjør du en matematisk regel om til et sant/usant-spørsmål som programmet kan bruke til å velge vei.",
    concepts: ["%", "==", "if", "else"],
    beforeQuestions: ["Hva er alltid sant om resten når et partall deles på 2?", "Hva er forskjellen på = og ==?", "Hvilke to mulige veier trenger programmet?"],
    successCriteria: ["divisjonsrest brukes", "sammenligning gjøres med ==", "både partall og oddetall håndteres"],
    testCases: [{ change: "tall = 14", expect: "14 er et partall" }, { change: "tall = 9", expect: "9 er et oddetall" }],
    hints: [
      { label: "Lite dytt", title: "Undersøk resten", body: "% gir resten etter en divisjon. Prøv å skrive ut 14 % 2 og 9 % 2." },
      { label: "Byggekloss", title: "Lag et sant/usant-spørsmål", body: "Et tall er partall når resten etter deling på 2 er lik 0.", code: "tall % 2 == 0" },
      { label: "Plan", title: "To programveier", body: "Bruk if til partallstilfellet. else kan samle alle andre heltall." },
      { label: "Nesten der", title: "Husk blokken", body: "Kolon åpner kodeblokken. Begge print-linjene må ha innrykk under riktig valg.", code: "if tall % 2 == 0:\n    print(\"partall\")\nelse:\n    print(\"oddetall\")" },
    ],
    scaffold: "tall = 14\n\n# Undersøk divisjonsresten med if\n# Skriv ett svar for hver av de to mulighetene",
    solutionCode: "tall = 14\n\nif tall % 2 == 0:\n    print(f\"{tall} er et partall.\")\nelse:\n    print(f\"{tall} er et oddetall.\")",
    solutionWalkthrough: ["tall % 2 finner divisjonsresten.", "== 0 spør om resten er null.", "if-grenen velges ved True; ellers velges else."],
    reflection: ["Hvorfor trenger ikke else et eget spørsmål?", "Hva skjer med negative heltall? Test -3 og -4."],
    extension: "Utvid programmet slik at det også forteller om tallet er positivt, negativt eller null.",
    checks: [{ label: "Koden undersøker divisjonsrest", codeIncludes: ["% 2", "== 0"] }, { label: "Resultatet klassifiserer tallet", outputIncludes: ["partall"] }],
  },
  {
    id: "hypotenuse",
    difficulty: "Enkel",
    title: "Finn hypotenusen",
    subject: "Pytagoras og variabler",
    estimatedMinutes: 20,
    teaser: "Regn ut den lengste siden uten å be et bibliotek om hele løsningen.",
    mission: "Katetene i en rettvinklet trekant er 3 cm og 4 cm. Lag et program som bruker Pytagoras til å finne hypotenusen og skriver et svar med enhet.",
    whyItMatters: "Du oversetter en kjent matematisk formel til små operasjoner Python kan følge. Hvert mellomsteg kan undersøkes.",
    concepts: ["Pytagoras", "**", "variabler", "avrunding"],
    beforeQuestions: ["Hvilken side er hypotenusen?", "Hva sier a² + b² = c²?", "Hvordan kan kvadratroten skrives som en potens?"],
    successCriteria: ["begge katetene opphøyes i andre", "summen får kvadratrot", "svaret viser 5 cm"],
    testCases: [{ change: "a = 3 og b = 4", expect: "5.0 cm" }, { change: "a = 5 og b = 12", expect: "13.0 cm" }],
    hints: [
      { label: "Lite dytt", title: "Finn først c²", body: "Pytagoras sier at kvadratet av hypotenusen er summen av kvadratene av katetene." },
      { label: "Byggekloss", title: "Potens i Python", body: "Python bruker to stjerner til potens.", code: "c_i_andre = a ** 2 + b ** 2" },
      { label: "Plan", title: "Gå fra c² til c", body: "Kvadratroten er det samme som å opphøye i 1/2. Skriv gjerne 0.5 så det er lett å lese." },
      { label: "Nesten der", title: "Det siste mellomsteget", body: "Bruk variabelen med c² til å finne selve c.", code: "c = c_i_andre ** 0.5" },
    ],
    scaffold: "a = 3\nb = 4\n\n# Regn først ut c_i_andre\n# Finn deretter c\n\n# Skriv et svar med cm",
    solutionCode: "a = 3\nb = 4\n\nc_i_andre = a ** 2 + b ** 2\nc = c_i_andre ** 0.5\n\nprint(f\"Hypotenusen er {c:.1f} cm.\")",
    solutionWalkthrough: ["3² + 4² blir 9 + 16 = 25.", "25 opphøyd i 0.5 er kvadratroten av 25.", "Hypotenusen er derfor 5 cm."],
    reflection: ["Hvorfor finner vi c² før vi finner c?", "Hvorfor er c alltid den lengste siden i en rettvinklet trekant?"],
    extension: "Gjør om programmet slik at hypotenusen og én katet er kjent, mens den andre kateten skal finnes.",
    shortcut: { title: "Senere: math.sqrt", body: "Når logikken er forstått, kan math.sqrt uttrykke «kvadratrot» direkte. Matematikken er den samme.", code: "import math\nc = math.sqrt(a ** 2 + b ** 2)" },
    checks: [{ label: "Koden bruker Pytagoras synlig", codeIncludes: ["a ** 2", "b ** 2", "+"] }, { label: "Resultatet viser hypotenusen", outputIncludes: ["5", "cm"] }],
  },
  {
    id: "multiplication-table",
    difficulty: "Enkel",
    title: "Lag en gangetabell",
    subject: "For-løkke og range",
    estimatedMinutes: 15,
    teaser: "Skriv regelen én gang og la Python gjøre ti runder.",
    mission: "Lag femgangen fra 1 · 5 til 10 · 5. Hver linje skal vise både regnestykket og svaret.",
    whyItMatters: "Løkker lar deg beskrive et mønster i stedet for å kopiere nesten like kodelinjer.",
    concepts: ["for", "range", "*", "f-tekst"],
    beforeQuestions: ["Hvilke tall skal forandre seg i hver runde?", "Hvilket tall er det samme hver gang?", "Hva må stoppverdien i range være for at 10 skal bli med?"],
    successCriteria: ["en for-løkke brukes", "range gir tallene 1 til 10", "hver utskrift viser regnestykke og svar"],
    testCases: [{ change: "gangen = 5", expect: "10 · 5 = 50" }, { change: "gangen = 7", expect: "10 · 7 = 70" }],
    hints: [
      { label: "Lite dytt", title: "Finn det som gjentas", body: "I hver runde trenger du ett nytt tall, mens variabelen gangen kan være den samme." },
      { label: "Byggekloss", title: "Tallene 1 til 10", body: "Stoppverdien i range er ikke med.", code: "range(1, 11)" },
      { label: "Plan", title: "Regn inni løkken", body: "I hver runde kan svar = tall * gangen beregnes med den nye tall-verdien." },
      { label: "Nesten der", title: "Vis hele regnestykket", body: "En f-tekst kan ha flere variabler og et regnestykke.", code: "print(f\"{tall} · {gangen} = {tall * gangen}\")" },
    ],
    scaffold: "gangen = 5\n\n# Lag en løkke som gir tallene 1 til 10\n# Skriv hele regnestykket med innrykk",
    solutionCode: "gangen = 5\n\nfor tall in range(1, 11):\n    svar = tall * gangen\n    print(f\"{tall} · {gangen} = {svar}\")",
    solutionWalkthrough: ["range(1, 11) gir 1 til og med 10.", "tall får én ny verdi i hver runde.", "Den innrykkede beregningen og utskriften gjentas ti ganger."],
    reflection: ["Hvorfor må stoppverdien være 11?", "Hvilken enkelt verdi endrer du for å lage sjugangen?"],
    extension: "Lag en dobbel løkke som skriver gangetabellene fra 1 til 10.",
    checks: [{ label: "Programmet bruker løkke og riktig range", codeIncludes: ["for", "range(1, 11)"] }, { label: "Tabellen kommer til 50", outputIncludes: ["50"] }],
  },
  {
    id: "ticket-price",
    difficulty: "Enkel",
    title: "Velg riktig billettpris",
    subject: "If, elif og else",
    estimatedMinutes: 20,
    teaser: "La alderen bestemme hvilken av tre priser som skal brukes.",
    mission: "Barn under 12 år betaler 60 kr, ungdom fra 12 til og med 17 år betaler 90 kr, og voksne betaler 140 kr. Lag et program som finner og skriver riktig pris.",
    whyItMatters: "Programmer tar ofte beslutninger ut fra grenser. Rekkefølgen på spørsmålene avgjør om alle verdier havner riktig.",
    concepts: ["if", "elif", "else", "grenser"],
    beforeQuestions: ["Hvilke tre aldersområder finnes?", "Kan én alder passe i to områder samtidig?", "Hvilken grense bør undersøkes først?"],
    successCriteria: ["alle tre grupper håndteres", "12 og 18 havner i riktig gruppe", "programmet skriver både alder og pris"],
    testCases: [{ change: "alder = 10", expect: "60 kr" }, { change: "alder = 12", expect: "90 kr" }, { change: "alder = 18", expect: "140 kr" }],
    hints: [
      { label: "Lite dytt", title: "Start nederst eller øverst", body: "Hvis du først spør om alder < 12, er alle som kommer til neste gren allerede minst 12." },
      { label: "Byggekloss", title: "Den første grensen", body: "Barn-grenen kan undersøkes med ett enkelt vilkår.", code: "if alder < 12:" },
      { label: "Plan", title: "Utnytt det Python allerede vet", body: "Når første spørsmål var usant, vet du allerede at alderen er minst 12. Derfor trenger elif bare å undersøke om alderen er under 18." },
      { label: "Nesten der", title: "Tre grener", body: "Gi pris en verdi i hver gren, og skriv svaret én gang etter hele valget.", code: "if alder < 12:\n    pris = 60\nelif alder < 18:\n    pris = 90\nelse:\n    pris = 140" },
    ],
    scaffold: "alder = 15\n\n# Bruk if, elif og else til å gi pris riktig verdi\n\n# Skriv alder og pris etter valget",
    solutionCode: "alder = 15\n\nif alder < 12:\n    pris = 60\nelif alder < 18:\n    pris = 90\nelse:\n    pris = 140\n\nprint(f\"En person på {alder} år betaler {pris} kr.\")",
    solutionWalkthrough: ["Første gren tar alle aldre under 12.", "De som når elif, er allerede minst 12; alder < 18 tar derfor 12–17.", "else tar 18 år og eldre.", "Utskriften kan stå etter valget fordi pris er laget i alle tre grener."],
    reflection: ["Hvorfor holder det å skrive elif alder < 18?", "Hva skjer med en negativ alder, og bør programmet håndtere det?"],
    extension: "Legg til en kontroll som gir en tydelig feilmelding hvis alder er mindre enn 0.",
    checks: [{ label: "Alle tre programveier finnes", codeIncludes: ["if", "elif", "else"] }, { label: "Resultatet viser ungdomsprisen", outputIncludes: ["90", "kr"] }],
  },

  {
    id: "right-triangle",
    difficulty: "Middels",
    title: "Er trekanten rettvinklet?",
    subject: "Pytagoras og vilkår",
    estimatedMinutes: 25,
    teaser: "Bruk tre sidelengder til å undersøke om Pytagoras stemmer.",
    mission: "En trekant har sidene 5, 12 og 13. Lag et program som undersøker om den er rettvinklet og skriver en forklaring.",
    whyItMatters: "Du kombinerer matematisk kunnskap med programmeringslogikk: beregn to uttrykk, sammenlign dem og velg et svar.",
    concepts: ["Pytagoras", "==", "if/else", "største side"],
    beforeQuestions: ["Hvilken side må være hypotenusen?", "Hvilke to uttrykk skal sammenlignes?", "Hva må være sant for en rettvinklet trekant?"],
    successCriteria: ["den lengste siden behandles som hypotenus", "a² + b² sammenlignes med c²", "begge mulige svar finnes"],
    testCases: [{ change: "a = 5, b = 12, c = 13", expect: "rettvinklet" }, { change: "a = 5, b = 6, c = 7", expect: "ikke rettvinklet" }],
    hints: [
      { label: "Lite dytt", title: "Plasser sidene riktig", body: "I Pytagoras må c være den lengste siden. I første løsning kan du avtale at variabelen c alltid er lengst." },
      { label: "Byggekloss", title: "Lag hver side av likheten", body: "Regn ut venstresiden og høyresiden hver for seg. Da kan de skrives ut og undersøkes.", code: "kateter_i_andre = a ** 2 + b ** 2\nhypotenus_i_andre = c ** 2" },
      { label: "Plan", title: "Sammenlign – ikke tildel", body: "Bruk == for å spørre om de to beregnede verdiene er like." },
      { label: "Nesten der", title: "Velg forklaring", body: "if tar tilfellet der Pytagoras stemmer; else tar det andre.", code: "if kateter_i_andre == hypotenus_i_andre:\n    print(\"Trekanten er rettvinklet.\")\nelse:\n    print(\"Trekanten er ikke rettvinklet.\")" },
    ],
    scaffold: "a = 5\nb = 12\nc = 13  # c skal være den lengste siden\n\n# Regn ut hver side av Pytagoras-likheten\n# Sammenlign uttrykkene med if\n# Skriv et svar for begge muligheter",
    solutionCode: "a = 5\nb = 12\nc = 13  # c er den lengste siden\n\nkateter_i_andre = a ** 2 + b ** 2\nhypotenus_i_andre = c ** 2\n\nif kateter_i_andre == hypotenus_i_andre:\n    print(f\"{a}² + {b}² = {c}². Trekanten er rettvinklet.\")\nelse:\n    print(f\"{a}² + {b}² er ikke lik {c}². Trekanten er ikke rettvinklet.\")",
    solutionWalkthrough: ["5² + 12² blir 25 + 144 = 169.", "13² blir også 169.", "Sammenligningen 169 == 169 er True.", "Python velger derfor if-grenen."],
    reflection: ["Hvorfor må den lengste siden stå alene på høyresiden?", "Hvordan kan programmet finne den lengste siden selv?"],
    extension: "La sidene ligge i en liste, sorter listen og bruk de to første som kateter og den siste som hypotenus.",
    shortcut: { title: "Mer robust med sortering", body: "Når grunnlogikken er forstått, kan sortering sikre at den lengste siden blir c uansett rekkefølge.", code: "sider = sorted([5, 13, 12])\na, b, c = sider" },
    checks: [{ label: "Begge sider av Pytagoras regnes ut", codeIncludes: ["a ** 2", "b ** 2", "c ** 2"] }, { label: "Programmet avgjør rettvinklet", outputIncludes: ["rettvinklet"] }],
  },
  {
    id: "missing-leg",
    difficulty: "Middels",
    title: "Finn den ukjente kateten",
    subject: "Pytagoras og omforming",
    estimatedMinutes: 25,
    teaser: "Denne gangen kjenner du hypotenusen og bare én katet.",
    mission: "Hypotenusen er 13 cm og én katet er 5 cm. Lag et program som finner den andre kateten ved å omforme Pytagoras.",
    whyItMatters: "Du må først gjøre matematisk algebra: flytte ett ledd til den andre siden. Deretter kan Python gjennomføre den nye oppskriften.",
    concepts: ["omforme formel", "minus", "kvadratrot", "mellomsteg"],
    beforeQuestions: ["Start med a² + b² = c². Hva blir b² alene?", "Hvorfor må c være større enn a?", "Hvilket regnesteg tar oss fra b² til b?"],
    successCriteria: ["formelen er riktig omformet", "kvadratroten tas etter subtraksjonen", "svaret viser 12 cm"],
    testCases: [{ change: "a = 5 og c = 13", expect: "12 cm" }, { change: "a = 6 og c = 10", expect: "8 cm" }],
    hints: [
      { label: "Lite dytt", title: "Flytt a²", body: "Trekk a² fra begge sider av a² + b² = c². Da står b² alene." },
      { label: "Byggekloss", title: "Den omformede formelen", body: "Kvadratet av den ukjente kateten er hypotenusens kvadrat minus den kjente katetens kvadrat.", code: "b_i_andre = c ** 2 - a ** 2" },
      { label: "Plan", title: "Ta kvadratroten til slutt", body: "Når b² er kjent, kan b finnes ved å opphøye i 0.5." },
      { label: "Nesten der", title: "To synlige mellomsteg", body: "Behold begge mellomsteg som variabler. Da blir løsningen lettere å forklare.", code: "b_i_andre = c ** 2 - a ** 2\nb = b_i_andre ** 0.5" },
    ],
    scaffold: "a = 5\nc = 13\n\n# Regn ut b_i_andre med den omformede formelen\n# Finn deretter b\n\n# Skriv svaret med cm",
    solutionCode: "a = 5\nc = 13\n\nb_i_andre = c ** 2 - a ** 2\nb = b_i_andre ** 0.5\n\nprint(f\"Den ukjente kateten er {b:.0f} cm.\")",
    solutionWalkthrough: ["b² = c² - a².", "13² - 5² blir 169 - 25 = 144.", "Kvadratroten av 144 er 12."],
    reflection: ["Hvorfor er det minus i denne formelen, men pluss når hypotenusen finnes?", "Hva skjer hvis a er større enn c, og hva forteller det om målene?"],
    extension: "Legg inn en kontroll som gir en forklaring hvis den oppgitte kateten er like lang eller lengre enn hypotenusen.",
    checks: [{ label: "Formelen er omformet med minus", codeIncludes: ["c ** 2", "- a ** 2"] }, { label: "Resultatet viser 12 cm", outputIncludes: ["12", "cm"] }],
  },
  {
    id: "largest-without-max",
    difficulty: "Middels",
    title: "Finn det største tallet selv",
    subject: "Løkke og tilstand",
    estimatedMinutes: 25,
    teaser: "Finn maksimum uten å bruke max – så ser du logikken bak verktøyet.",
    mission: "Finn det største tallet i listen [7, 12, 4, 19, 8] uten å bruke max(). Programmet skal skrive både største verdi og hvordan den ble funnet.",
    whyItMatters: "Du øver på å la en variabel huske det beste svaret så langt. Det samme mønsteret brukes i rekorder, søk og spill.",
    concepts: ["liste", "for", "if", "oppdatere variabel"],
    beforeQuestions: ["Hva kan være vårt første «største så langt»?", "Når skal denne verdien byttes ut?", "Hva må løkken sammenligne i hver runde?"],
    successCriteria: ["max() brukes ikke", "en variabel husker største verdi så langt", "alle listeverdiene undersøkes"],
    testCases: [{ change: "[7, 12, 4, 19, 8]", expect: "19" }, { change: "[-8, -2, -15]", expect: "-2" }],
    hints: [
      { label: "Lite dytt", title: "Start med en virkelig verdi", body: "La største være den første verdien i listen. Da virker programmet også når alle tall er negative." },
      { label: "Byggekloss", title: "Husk første verdi", body: "Indeks 0 er den første plassen.", code: "storste = tall[0]" },
      { label: "Plan", title: "Én utfordrer om gangen", body: "Gå gjennom listen. Hvis den nye verdien er større enn rekorden, får storste den nye verdien." },
      { label: "Nesten der", title: "Oppdater rekorden", body: "Tildelingen må ligge med innrykk under if, som igjen ligger under løkken.", code: "for verdi in tall:\n    if verdi > storste:\n        storste = verdi" },
    ],
    scaffold: "tall = [7, 12, 4, 19, 8]\n\n# La storste starte med en virkelig verdi fra listen\n# Gå gjennom listen og oppdater rekorden\n\n# Skriv største verdi",
    solutionCode: "tall = [7, 12, 4, 19, 8]\n\nstorste = tall[0]\n\nfor verdi in tall:\n    if verdi > storste:\n        storste = verdi\n        print(f\"Ny rekord: {storste}\")\n\nprint(f\"Det største tallet er {storste}.\")",
    solutionWalkthrough: ["Rekorden starter som 7.", "12 slår 7 og blir ny rekord.", "4 slår ikke 12.", "19 slår 12 og blir stående som sluttresultat."],
    reflection: ["Hvorfor er storste = 0 en dårlig start hvis alle tall er negative?", "Hvordan ville du endret programmet for å finne det minste tallet?"],
    extension: "Finn både minste og største verdi i den samme løkken uten min() eller max().",
    shortcut: { title: "Senere: innebygd max", body: "Når du forstår søkelogikken, er max(tall) den tydelige og effektive løsningen i vanlig kode.", code: "storste = max(tall)" },
    checks: [{ label: "Koden bygger maksimum selv", codeIncludes: ["for", "if", ">"] }, { label: "Resultatet finner 19", outputIncludes: ["19"] }],
  },
  {
    id: "average-analysis",
    difficulty: "Middels",
    title: "Analyser målinger",
    subject: "Lister og gjennomsnitt",
    estimatedMinutes: 25,
    teaser: "Finn gjennomsnittet og tell målinger som ligger over det.",
    mission: "For målingene [12, 15, 11, 18, 14] skal programmet finne gjennomsnittet og telle hvor mange målinger som er høyere enn gjennomsnittet.",
    whyItMatters: "Du kombinerer aggregering og sammenligning: først lager du en referanseverdi, så undersøker du hvert datapunkt mot den.",
    concepts: ["liste", "sum", "len", "løkke", "teller"],
    beforeQuestions: ["Hvordan regnes gjennomsnitt?", "Hva må være kjent før vi kan sammenligne hver måling?", "Hvordan kan en teller økes hver gang et vilkår er sant?"],
    successCriteria: ["gjennomsnittet beregnes fra listen", "hver måling sammenlignes med gjennomsnittet", "telleren starter på 0 og økes riktig"],
    testCases: [{ change: "[12, 15, 11, 18, 14]", expect: "Gjennomsnitt 14.0 og 2 over" }],
    hints: [
      { label: "Lite dytt", title: "Finn referansen først", body: "Gjennomsnittet er summen av alle målingene delt på antallet målinger." },
      { label: "Byggekloss", title: "Python kan summere og telle", body: "sum gir totalsummen, og len gir antall listeverdier.", code: "gjennomsnitt = sum(maallinger) / len(maallinger)" },
      { label: "Plan", title: "Lag en teller", body: "Start antall_over på 0. Gå gjennom målingene og øk telleren bare når målingen er større enn gjennomsnittet." },
      { label: "Nesten der", title: "Tell sanne treff", body: "Tellerens oppdatering må ha innrykk under if.", code: "for verdi in maallinger:\n    if verdi > gjennomsnitt:\n        antall_over += 1" },
    ],
    scaffold: "maallinger = [12, 15, 11, 18, 14]\n\n# Regn ut gjennomsnittet\n# Lag en teller som starter på 0\n# Gå gjennom målingene og tell verdier over gjennomsnittet\n\n# Skriv begge svarene",
    solutionCode: "maallinger = [12, 15, 11, 18, 14]\n\ngjennomsnitt = sum(maallinger) / len(maallinger)\nantall_over = 0\n\nfor verdi in maallinger:\n    if verdi > gjennomsnitt:\n        antall_over += 1\n\nprint(f\"Gjennomsnittet er {gjennomsnitt:.1f}.\")\nprint(f\"{antall_over} målinger er over gjennomsnittet.\")",
    solutionWalkthrough: ["Summen 70 deles på 5 og gir 14.", "Telleren begynner på 0.", "15 og 18 er større enn 14, så telleren økes to ganger."],
    reflection: ["Hvorfor må gjennomsnittet beregnes før løkken?", "Hva er forskjellen på høyere enn og høyere enn eller lik gjennomsnittet?"],
    extension: "Lag en ny liste som inneholder bare målingene over gjennomsnittet.",
    checks: [{ label: "Gjennomsnittet bruker sum og len", codeIncludes: ["sum(", "len("] }, { label: "Resultatet viser to treff", outputIncludes: ["14", "2"] }],
  },
  {
    id: "count-vowels",
    difficulty: "Middels",
    title: "Tell vokaler i en tekst",
    subject: "Tekst, løkke og medlemskap",
    estimatedMinutes: 25,
    teaser: "La Python undersøke én bokstav om gangen.",
    mission: "Tell hvor mange vokaler som finnes i teksten «Programmering er gøy». Bruk en løkke og en teller.",
    whyItMatters: "Tekst er også en samling. Ved å gå gjennom tegnene kan vi bygge søk, kontroll, statistikk og enkle språkverktøy.",
    concepts: ["tekst", "for", "in", "teller"],
    beforeQuestions: ["Hva får en for-løkke når den går gjennom en tekst?", "Hvordan kan alle vokalene samles i én tekst?", "Hva skal gjøre at telleren øker?"],
    successCriteria: ["teksten gås gjennom tegn for tegn", "in brukes til å undersøke vokalene", "store og små bokstaver håndteres"],
    testCases: [{ change: "Programmering er gøy", expect: "7 vokaler" }, { change: "PYTHON", expect: "1 vokal" }],
    hints: [
      { label: "Lite dytt", title: "En tekst kan være samlingen", body: "for bokstav in tekst gir bokstav ett tegn om gangen." },
      { label: "Byggekloss", title: "Samle vokalene", body: "Du kan undersøke om en bokstav finnes i en tekst som inneholder alle vokalene.", code: "vokaler = \"aeiouyæøå\"" },
      { label: "Plan", title: "Gjør teksten lik før sammenligning", body: "tekst.lower() lager små bokstaver. Da trenger du ikke både A og a i vokallisten." },
      { label: "Nesten der", title: "Tell medlemskap", body: "Øk telleren når bokstaven finnes i vokaler.", code: "for bokstav in tekst.lower():\n    if bokstav in vokaler:\n        antall += 1" },
    ],
    scaffold: "tekst = \"Programmering er gøy\"\nvokaler = \"aeiouyæøå\"\n\n# Lag en teller\n# Gå gjennom teksten bokstav for bokstav\n# Øk telleren når bokstaven er en vokal\n\n# Skriv svaret",
    solutionCode: "tekst = \"Programmering er gøy\"\nvokaler = \"aeiouyæøå\"\nantall = 0\n\nfor bokstav in tekst.lower():\n    if bokstav in vokaler:\n        antall += 1\n\nprint(f\"Teksten har {antall} vokaler.\")",
    solutionWalkthrough: ["lower lager en sammenlignbar tekst med små bokstaver.", "Løkken gir ett tegn om gangen.", "in blir True når tegnet finnes i vokalteksten.", "Telleren økes bare ved slike treff."],
    reflection: ["Hvorfor er mellomrom og punktum uproblematiske?", "Er y alltid en vokal på norsk? Hvordan kan oppgaven tilpasses en annen regel?"],
    extension: "Lag en ordbok som teller hvor mange ganger hver vokal forekommer.",
    checks: [{ label: "Koden går gjennom teksten og bruker in", codeIncludes: ["for", " in vokaler"] }, { label: "Resultatet viser antall vokaler", outputIncludes: ["vokal"] }],
  },
  {
    id: "turtle-polygon",
    difficulty: "Middels",
    title: "Tegn en valgfri mangekant",
    subject: "Turtle, løkke og geometri",
    estimatedMinutes: 30,
    teaser: "Én geometrisk regel skal kunne tegne trekant, femkant og åttekant.",
    mission: "Lag variablene antall_sider og sidelengde. Bruk dem til å tegne en regulær mangekant som lukker seg.",
    whyItMatters: "Du gjør geometrien generell: I stedet for en oppskrift for hvert polygon lager du én algoritme styrt av variabler.",
    concepts: ["Turtle", "360°", "for-løkke", "variabler"],
    beforeQuestions: ["Hvor mange grader snur Turtle til sammen rundt hele figuren?", "Hvordan finner du dreievinkelen for n like sider?", "Hvilke kommandoer må gjentas?"],
    successCriteria: ["dreievinkelen regnes fra antall sider", "forward og left/right ligger i løkken", "figuren lukker seg for flere sideantall"],
    testCases: [{ change: "antall_sider = 3", expect: "en lukket trekant" }, { change: "antall_sider = 8", expect: "en lukket åttekant" }],
    hints: [
      { label: "Lite dytt", title: "En hel omdreining", body: "Når figuren er ferdig, har Turtle snudd til sammen 360 grader." },
      { label: "Byggekloss", title: "Finn vinkelen", body: "Fordel 360 grader likt på antallet sider.", code: "vinkel = 360 / antall_sider" },
      { label: "Plan", title: "Én side per runde", body: "Gjenta akkurat antall_sider ganger. Hver runde tegner én side og snur før neste." },
      { label: "Nesten der", title: "Bevegelse og sving må gjentas", body: "Begge Turtle-kommandoene trenger samme innrykk.", code: "for side in range(antall_sider):\n    forward(sidelengde)\n    left(vinkel)" },
    ],
    scaffold: "from turtle import *\n\nantall_sider = 5\nsidelengde = 100\n\n# Regn ut dreievinkelen\n# Gjenta bevegelse og sving riktig antall ganger\n\ndone()",
    solutionCode: "from turtle import *\n\nantall_sider = 5\nsidelengde = 100\nvinkel = 360 / antall_sider\n\nfor side in range(antall_sider):\n    forward(sidelengde)\n    left(vinkel)\n\ndone()",
    solutionWalkthrough: ["For en femkant blir vinkelen 360 / 5 = 72°.", "Løkken kjører fem ganger.", "Hver runde tegner én side og snur 72°.", "Fem svinger blir til sammen 360°, så figuren lukker seg."],
    reflection: ["Hva skjer med vinkelen når antall sider øker?", "Når begynner figuren å ligne en sirkel?"],
    extension: "Tegn mangekanter med 3 til 10 sider ved siden av hverandre. Bruk penup, goto og pendown til å flytte uten strek.",
    checks: [{ label: "Vinkelen bygger på 360 grader", codeIncludes: ["360 / antall_sider"] }, { label: "Turtle bruker løkke", codeIncludes: ["for", "forward", "left"] }],
  },

  {
    id: "triangle-classifier",
    difficulty: "Utfordrende",
    title: "Bygg en trekantdetektiv",
    subject: "Geometri og sammensatte vilkår",
    estimatedMinutes: 40,
    teaser: "Kontroller først om sidene kan bli en trekant, og klassifiser den deretter.",
    mission: "For tre sidelengder skal programmet først undersøke trekantulikheten. Hvis trekanten er gyldig, skal det fortelle om den er likesidet, likebeint eller uliksidet – og om den er rettvinklet.",
    whyItMatters: "Et større problem blir håndterlig når kontrollene gjøres i riktig rekkefølge. Programmet skal ikke klassifisere noe som ikke kan være en trekant.",
    concepts: ["and", "elif", "sortering", "Pytagoras", "validering"],
    beforeQuestions: ["Hva må være sant om summen av de to korteste sidene?", "Hvilken klassifisering bør gjøres først?", "Hvordan kan sortering hjelpe Pytagoras-kontrollen?"],
    successCriteria: ["ugyldige trekanter stoppes først", "alle tre sidetyper kan identifiseres", "rettvinklethet undersøkes med sorterte sider"],
    testCases: [{ change: "5, 5, 5", expect: "likesidet, ikke rettvinklet" }, { change: "5, 12, 13", expect: "uliksidet og rettvinklet" }, { change: "2, 3, 8", expect: "ikke en gyldig trekant" }],
    hints: [
      { label: "Lite dytt", title: "Gyldighet før type", body: "Sorter sidene. Da holder det å undersøke om de to korteste til sammen er lengre enn den lengste." },
      { label: "Byggekloss", title: "Gi sidene faste roller", body: "Etter sortering kan listen pakkes ut fra kortest til lengst.", code: "a, b, c = sorted([side1, side2, side3])" },
      { label: "Plan", title: "Lag lag av beslutninger", body: "Ytterste if kontrollerer gyldighet. Inne i den kan ett if/elif/else finne sidetypen, og et eget if finne rettvinklethet." },
      { label: "Nesten der", title: "To uavhengige klassifiseringer", body: "Sidetypen og rettvinkletheten er to ulike egenskaper. Lagre dem i hver sin variabel før utskrift.", code: "if a == b == c:\n    sidetype = \"likesidet\"\nelif a == b or b == c:\n    sidetype = \"likebeint\"\nelse:\n    sidetype = \"uliksidet\"" },
    ],
    scaffold: "side1 = 5\nside2 = 12\nside3 = 13\n\n# Sorter og pakk ut sidene som a, b og c\n# Kontroller trekantulikheten først\n# Finn sidetypen\n# Undersøk Pytagoras\n# Skriv en samlet forklaring",
    solutionCode: "side1 = 5\nside2 = 12\nside3 = 13\n\na, b, c = sorted([side1, side2, side3])\n\nif a + b <= c:\n    print(\"Sidelengdene kan ikke danne en trekant.\")\nelse:\n    if a == b == c:\n        sidetype = \"likesidet\"\n    elif a == b or b == c:\n        sidetype = \"likebeint\"\n    else:\n        sidetype = \"uliksidet\"\n\n    if a ** 2 + b ** 2 == c ** 2:\n        vinkeltype = \"rettvinklet\"\n    else:\n        vinkeltype = \"ikke rettvinklet\"\n\n    print(f\"Trekanten er {sidetype} og {vinkeltype}.\")",
    solutionWalkthrough: ["Sortering gjør c til den lengste siden.", "a + b <= c avslører ugyldige sider før videre arbeid.", "Likheter mellom sidene bestemmer sidetypen.", "Pytagoras bestemmer rettvinklethet uavhengig av sidetypen."],
    reflection: ["Hvorfor bør ugyldige trekanter stoppes først?", "Kan en rettvinklet trekant være likebeint? Finn et eksempel eller forklar hvorfor ikke."],
    extension: "Bruk omtrent-lik sammenligning med en liten toleranse slik at desimaltall som 1, 1 og 1.414 også kan undersøkes.",
    checks: [{ label: "Koden validerer før klassifisering", codeIncludes: ["a + b <= c"] }, { label: "Koden finner både side- og vinkeltype", codeIncludes: ["sidetype", "vinkeltype", "** 2"] }],
  },
  {
    id: "prime-number",
    difficulty: "Utfordrende",
    title: "Undersøk om et tall er et primtall",
    subject: "Løkke, vilkår og tidlig stopp",
    estimatedMinutes: 40,
    teaser: "Let systematisk etter en divisor – og stopp når du finner en.",
    mission: "Lag et program som undersøker om 97 er et primtall. Løsningen skal teste mulige divisorer og forklare resultatet.",
    whyItMatters: "Dette er et ekte algoritmeproblem: Du må velge hva som skal prøves, hva som teller som bevis, og når søket kan avsluttes.",
    concepts: ["for", "%", "boolsk variabel", "break"],
    beforeQuestions: ["Hvilke to divisorer har alle primtall?", "Hva viser at et tall ikke er primtall?", "Hvorfor trenger vi ikke prøve divisoren 1?"],
    successCriteria: ["tall under 2 håndteres", "mulige divisorer testes med %", "søket stopper når en divisor finnes"],
    testCases: [{ change: "tall = 97", expect: "primtall" }, { change: "tall = 91", expect: "ikke primtall; 7 er divisor" }, { change: "tall = 1", expect: "ikke primtall" }],
    hints: [
      { label: "Lite dytt", title: "Let etter motbevis", body: "Det holder å finne én divisor mellom 2 og tallet - 1 for å bevise at tallet ikke er et primtall." },
      { label: "Byggekloss", title: "Test delelighet", body: "Hvis divisjonsresten er 0, går divisoren opp i tallet.", code: "tall % divisor == 0" },
      { label: "Plan", title: "Anta sant, let etter feil", body: "Start med er_primtall = True. Hvis en divisor finnes, bytt til False, lagre divisoren og stopp løkken." },
      { label: "Nesten der", title: "Søk og stopp", body: "break gjør at unødvendige divisorer ikke prøves etter at svaret er avgjort.", code: "for divisor in range(2, tall):\n    if tall % divisor == 0:\n        er_primtall = False\n        funnet_divisor = divisor\n        break" },
    ],
    scaffold: "tall = 97\n\n# Håndter tall under 2\n# Anta deretter at tallet er et primtall\n# Let etter en divisor fra 2 og oppover\n# Stopp når du finner en\n\n# Skriv en forklaring",
    solutionCode: "tall = 97\n\nif tall < 2:\n    print(f\"{tall} er ikke et primtall.\")\nelse:\n    er_primtall = True\n    funnet_divisor = None\n\n    for divisor in range(2, tall):\n        if tall % divisor == 0:\n            er_primtall = False\n            funnet_divisor = divisor\n            break\n\n    if er_primtall:\n        print(f\"{tall} er et primtall.\")\n    else:\n        print(f\"{tall} er ikke et primtall fordi det kan deles på {funnet_divisor}.\")",
    solutionWalkthrough: ["97 er ikke under 2, så søket starter.", "Ingen divisor fra 2 til 96 gir rest 0.", "er_primtall forblir derfor True.", "For 91 ville divisor 7 gitt rest 0 og stoppet løkken."],
    reflection: ["Hvorfor er det nok å finne én divisor?", "Hvor langt må vi egentlig lete før alle mulige faktorpar er undersøkt?"],
    extension: "Gjør søket mer effektivt ved å prøve divisorer bare til og med kvadratroten av tallet.",
    checks: [{ label: "Koden tester divisjonsrest i en løkke", codeIncludes: ["for", "% divisor", "== 0"] }, { label: "Søket kan stoppe tidlig", codeIncludes: ["break"] }],
  },
  {
    id: "growth-threshold",
    difficulty: "Utfordrende",
    title: "Når passeres en grense?",
    subject: "Vekstfaktor og while-løkke",
    estimatedMinutes: 35,
    teaser: "La løkken finne tidspunktet i stedet for at du gjetter det.",
    mission: "En konto starter med 1000 kr og vokser med 8 % per år. Finn det første året saldoen er minst 1500 kr, og skriv utviklingen år for år.",
    whyItMatters: "Når antall gjentakelser ikke er kjent på forhånd, kan et vilkår styre løkken. Dette kobler modellering og algoritmisk tenkning.",
    concepts: ["while", "vekstfaktor", "teller", ">="],
    beforeQuestions: ["Hva er vekstfaktoren ved 8 % økning?", "Hvilket vilkår betyr at løkken skal fortsette?", "Hvilke to verdier må oppdateres hvert år?"],
    successCriteria: ["vekstfaktor 1.08 brukes", "saldo og år oppdateres i løkken", "løkken stopper ved første saldo på minst 1500"],
    testCases: [{ change: "start 1000, vekst 8 %, grense 1500", expect: "år 6" }],
    hints: [
      { label: "Lite dytt", title: "Vi kjenner ikke antall runder", body: "Derfor passer while bedre enn en for-løkke med et bestemt antall år." },
      { label: "Byggekloss", title: "Fortsett mens saldoen er for lav", body: "Løkken skal kjøre så lenge saldo ennå ikke har nådd grensen.", code: "while saldo < grense:" },
      { label: "Plan", title: "Ett år per runde", body: "Gang saldo med vekstfaktoren, og øk år med 1. Begge linjene må være inne i løkken." },
      { label: "Nesten der", title: "Oppdater modellen", body: "*= bruker den gamle saldoen, ganger med 1.08 og lagrer den nye.", code: "saldo *= vekstfaktor\naar += 1" },
    ],
    scaffold: "saldo = 1000\nvekstfaktor = 1.08\ngrense = 1500\naar = 0\n\n# Gjenta mens saldoen er lavere enn grensen\n# Oppdater saldo og år\n# Skriv gjerne utviklingen inne i løkken\n\n# Skriv hvilket år grensen ble nådd",
    solutionCode: "saldo = 1000\nvekstfaktor = 1.08\ngrense = 1500\naar = 0\n\nwhile saldo < grense:\n    saldo *= vekstfaktor\n    aar += 1\n    print(f\"Etter år {aar}: {saldo:.2f} kr\")\n\nprint(f\"Grensen passeres første gang etter {aar} år.\")",
    solutionWalkthrough: ["Løkken starter fordi 1000 < 1500.", "Hver runde representerer ett år.", "Saldoen oppdateres før den testes på nytt.", "Etter seks runder er saldoen for første gang minst 1500."],
    reflection: ["Hvorfor bruker vilkåret < og ikke <=?", "Hva ville skjedd hvis linjen saldo *= vekstfaktor lå utenfor løkken?"],
    extension: "Legg til et årlig innskudd på 500 kr og undersøk om innskuddet skal legges til før eller etter rentene.",
    checks: [{ label: "Koden bruker en styrt while-løkke", codeIncludes: ["while saldo < grense"] }, { label: "Begge tilstandsverdiene oppdateres", codeIncludes: ["saldo *=", "aar += 1"] }, { label: "Resultatet finner år 6", outputIncludes: ["6"] }],
  },
  {
    id: "dice-simulation",
    difficulty: "Utfordrende",
    title: "Simuler summen av to terninger",
    subject: "Sannsynlighet og simulering",
    estimatedMinutes: 40,
    teaser: "Undersøk hvor ofte summen 7 dukker opp i mange tilfeldige forsøk.",
    mission: "Kast to digitale terninger 10 000 ganger. Tell hvor ofte summen blir 7, regn ut andelen og sammenlign med den teoretiske sannsynligheten 1/6.",
    whyItMatters: "Simulering lar oss undersøke tilfeldighet empirisk. Samtidig må vi være presise med forsøk, teller og andel.",
    concepts: ["random", "for", "teller", "andel", "avvik"],
    beforeQuestions: ["Hva skjer i ett forsøk?", "Når skal telleren økes?", "Hvordan går vi fra antall treff til andel?"],
    successCriteria: ["begge terningene kastes i hver runde", "bare sum 7 telles", "andelen og avviket fra 1/6 beregnes"],
    testCases: [{ change: "antall_forsok = 10000", expect: "en andel nær 16,7 %, men ikke nødvendigvis nøyaktig" }],
    hints: [
      { label: "Lite dytt", title: "Bygg ett forsøk først", body: "Få to randint-kall og summen til å virke før du lager løkken." },
      { label: "Byggekloss", title: "Én terning", body: "Begge grensene er med i randint.", code: "terning1 = random.randint(1, 6)" },
      { label: "Plan", title: "Tell treff", body: "Start antall_sju på 0. Inne i løkken kaster du begge terninger og øker telleren bare hvis summen er 7." },
      { label: "Nesten der", title: "Fra treff til andel", body: "Del treff på antall forsøk etter løkken. Format :.2% viser andelen som prosent.", code: "andel = antall_sju / antall_forsok\nprint(f\"Andel sum 7: {andel:.2%}\")" },
    ],
    scaffold: "import random\n\nantall_forsok = 10_000\nantall_sju = 0\n\n# Gjenta forsøket riktig antall ganger\n# Kast to terninger i hver runde\n# Tell når summen er 7\n\n# Regn ut andel og avvik fra 1/6\n# Skriv resultatet",
    solutionCode: "import random\n\nantall_forsok = 10_000\nantall_sju = 0\n\nfor forsok in range(antall_forsok):\n    terning1 = random.randint(1, 6)\n    terning2 = random.randint(1, 6)\n\n    if terning1 + terning2 == 7:\n        antall_sju += 1\n\nandel = antall_sju / antall_forsok\nteoretisk = 1 / 6\navvik = abs(andel - teoretisk)\n\nprint(f\"Sum 7 kom {antall_sju} ganger.\")\nprint(f\"Simulert andel: {andel:.2%}\")\nprint(f\"Teoretisk andel: {teoretisk:.2%}\")\nprint(f\"Avvik: {avvik:.2%}\")",
    solutionWalkthrough: ["Hvert forsøk lager to uavhengige kast.", "Telleren økes bare for de seks kombinasjonene som gir sum 7.", "Treff deles på 10 000 for å gi simulert andel.", "abs gjør avviket positivt uansett hvilken andel som er størst."],
    reflection: ["Hvorfor varierer resultatet fra kjøring til kjøring?", "Hva skjer vanligvis med avviket når antall forsøk økes?"],
    extension: "Tell alle mulige summer fra 2 til 12 i en liste eller ordbok, og tegn resultatet som et stolpediagram.",
    checks: [{ label: "Begge terninger kastes i løkken", codeIncludes: ["random.randint", "for"] }, { label: "Sum 7 telles", codeIncludes: ["terning1 + terning2 == 7"] }, { label: "Andelen beregnes", codeIncludes: ["/ antall_forsok"] }],
  },
  {
    id: "caesar-cipher",
    difficulty: "Utfordrende",
    title: "Lag en enkel kodeknekker",
    subject: "Tekst, indeks og algoritme",
    estimatedMinutes: 45,
    teaser: "Flytt hver bokstav tre plasser fram i alfabetet – og håndter slutten av alfabetet.",
    mission: "Lag et Cæsar-chiffer for små bokstaver a–z. Teksten «python» med forskyvning 3 skal bli «sbwkrq». Mellomrom skal beholdes.",
    whyItMatters: "Du må bryte tekstbehandling ned til én bokstav, finne posisjonen, regne ut ny posisjon og bygge et nytt resultat.",
    concepts: ["tekst", "find", "%", "løkke", "bygge resultat"],
    beforeQuestions: ["Hvordan kan alfabetet lagres slik at hver bokstav har en indeks?", "Hva skal skje med z når den flyttes fram?", "Hvordan kan resultatteksten bygges én bokstav om gangen?"],
    successCriteria: ["hver bokstav behandles i en løkke", "% brukes til å gå rundt slutten av alfabetet", "tegn utenfor alfabetet beholdes"],
    testCases: [{ change: "python, forskyvning 3", expect: "sbwkrq" }, { change: "xyz, forskyvning 3", expect: "abc" }, { change: "hei du", expect: "khl gx" }],
    hints: [
      { label: "Lite dytt", title: "Alfabet som oppslagstabell", body: "Lagre bokstavene i én tekst. Indeksen er bokstavens plassnummer." },
      { label: "Byggekloss", title: "Finn gammel plass", body: "find gir indeksen til bokstaven eller -1 hvis tegnet ikke finnes.", code: "gammel_indeks = alfabet.find(bokstav)" },
      { label: "Plan", title: "Gå rundt slutten", body: "Legg forskyvningen til indeksen. % len(alfabet) gjør at 26 blir 0, 27 blir 1 og så videre." },
      { label: "Nesten der", title: "Bygg svaret", body: "Start kodet = \"\". Legg én ny bokstav til i hver runde; behold tegnet hvis det ikke finnes i alfabetet.", code: "ny_indeks = (gammel_indeks + forskyvning) % len(alfabet)\nkodet += alfabet[ny_indeks]" },
    ],
    scaffold: "alfabet = \"abcdefghijklmnopqrstuvwxyz\"\ntekst = \"python\"\nforskyvning = 3\nkodet = \"\"\n\n# Gå gjennom teksten bokstav for bokstav\n# Finn gammel indeks\n# Beregn ny indeks med %\n# Legg ny bokstav til kodet\n# Behold tegn som ikke finnes i alfabetet\n\nprint(kodet)",
    solutionCode: "alfabet = \"abcdefghijklmnopqrstuvwxyz\"\ntekst = \"python\"\nforskyvning = 3\nkodet = \"\"\n\nfor bokstav in tekst.lower():\n    gammel_indeks = alfabet.find(bokstav)\n\n    if gammel_indeks == -1:\n        kodet += bokstav\n    else:\n        ny_indeks = (gammel_indeks + forskyvning) % len(alfabet)\n        kodet += alfabet[ny_indeks]\n\nprint(f\"Kodet tekst: {kodet}\")",
    solutionWalkthrough: ["p har indeks 15; 15 + 3 gir 18, som er s.", "Hver ny bokstav legges bakerst i resultatteksten.", "% 26 gjør at en indeks etter z begynner på a igjen.", "Mellomrom gir indeks -1 og beholdes uendret."],
    reflection: ["Hvorfor trenger vi % selv om eksemplet «python» ikke går forbi z?", "Hvordan kan samme program dekode teksten?"],
    extension: "Utvid alfabetet med æ, ø og å, og lag en funksjon som kan både kode og dekode med positiv eller negativ forskyvning.",
    checks: [{ label: "Koden behandler én bokstav om gangen", codeIncludes: ["for bokstav in"] }, { label: "Indeksen går rundt alfabetet", codeIncludes: ["% len(alfabet)"] }, { label: "Resultatet koder python", outputIncludes: ["sbwkrq"] }],
  },
  {
    id: "turtle-spiral",
    difficulty: "Utfordrende",
    title: "Design et geometrisk spiralmønster",
    subject: "Turtle, mønster og parametere",
    estimatedMinutes: 40,
    teaser: "La lengden vokse litt for hver strek og undersøk hvordan vinkelen endrer uttrykket.",
    mission: "Lag et Turtle-mønster med minst 80 streker. Lengden skal øke i hver runde. Bruk variabler for antall streker, vekst og vinkel slik at mønsteret er lett å eksperimentere med og eksportere som SVG.",
    whyItMatters: "Skapende programmering kombinerer algoritmer, geometri og design. Små parameterendringer kan gi helt nye uttrykk.",
    concepts: ["Turtle", "akkumulering", "vinkel", "parametere", "SVG"],
    beforeQuestions: ["Hvilken verdi må endres i hver runde for at spiralen skal vokse?", "Hva skjer hvis vinkelen er nøyaktig 90°?", "Hvilke innstillinger bør stå som variabler øverst?"],
    successCriteria: ["mønsteret styres av tydelige variabler", "lengden oppdateres i løkken", "minst 80 streker tegnes uten kopiert kode"],
    testCases: [{ change: "vinkel 90°", expect: "et firkantet spiralmønster" }, { change: "vinkel 91°", expect: "mønsteret roterer gradvis" }, { change: "vinkel 137°", expect: "et tett og annerledes stjernemønster" }],
    hints: [
      { label: "Lite dytt", title: "En tilstand som vokser", body: "Lag lengde før løkken. Etter hver strek kan lengde økes med variabelen vekst." },
      { label: "Byggekloss", title: "Oppdater lengden", body: "+= betyr «legg til og lagre den nye verdien».", code: "lengde += vekst" },
      { label: "Plan", title: "Tre handlinger per runde", body: "Tegn framover, snu, og øk lengden. Rekkefølgen påvirker hvor den første veksten vises." },
      { label: "Nesten der", title: "Den generelle mønsterløkken", body: "Alle tre handlingene må ligge med innrykk i løkken.", code: "for strek in range(antall_streker):\n    forward(lengde)\n    left(vinkel)\n    lengde += vekst" },
    ],
    scaffold: "from turtle import *\n\nantall_streker = 100\nlengde = 5\nvekst = 2\nvinkel = 91\n\n# Velg gjerne farge og tykkelse\n# Tegn, snu og øk lengden i en løkke\n\ndone()",
    solutionCode: "from turtle import *\n\nantall_streker = 100\nlengde = 5\nvekst = 2\nvinkel = 91\n\ncolor(\"#2f6b5f\")\npensize(2)\n\nfor strek in range(antall_streker):\n    forward(lengde)\n    left(vinkel)\n    lengde += vekst\n\ndone()",
    solutionWalkthrough: ["Første strek er 5 enheter.", "Etter hver runde økes lengden med 2.", "91° er litt mer enn et firkanthjørne, så hele spiralen roterer gradvis.", "Variablene øverst gjør designet lett å utforske."],
    reflection: ["Hvorfor får 90° og 91° så forskjellig resultat?", "Hvilke kombinasjoner av vinkel og antall streker gir symmetri?"],
    extension: "Bruk en liste med farger, bytt farge i løkken og eksporter mønsteret fra Skaperverkstedet som SVG til vinylkutter eller laser.",
    checks: [{ label: "Mønsteret styres av variabler", codeIncludes: ["antall_streker", "vekst", "vinkel"] }, { label: "Lengden vokser i løkken", codeIncludes: ["lengde += vekst"] }, { label: "Turtle tegner og snur", codeIncludes: ["forward", "left"] }],
  },
];
