import type { PythonCommand } from "./pythonCommands";

// Utvidelser til det søkbare kommandobiblioteket. Hver oppføring skal kunne
// finnes både med Python-navnet og med ord en nybegynner faktisk ville søkt på.
export const mathLibraryCommands: PythonCommand[] = [
  {
    id: "math-ceil-floor",
    category: "Tall og statistikk",
    syntax: "math.ceil(tall) / math.floor(tall)",
    title: "ceil runder opp og floor runder ned",
    summary: "ceil går opp til nærmeste heltall, mens floor går ned.",
    explanation: "Importer math først. Dette er styrt avrunding: math.ceil(3.1) blir 4 og math.floor(3.9) blir 3. Det er forskjellig fra round, som går til nærmeste verdi.",
    example: "import math\n\nprint(math.ceil(3.1))\nprint(math.floor(3.9))",
    result: "4\n3",
    keywords: ["rund opp", "rund ned", "tak", "gulv", "ceil", "floor", "heltall"],
  },
  {
    id: "math-gcd-lcm",
    category: "Tall og statistikk",
    syntax: "math.gcd(a, b) / math.lcm(a, b)",
    title: "gcd og lcm finner felles faktorer og multipler",
    summary: "gcd gir største felles divisor; lcm gir minste felles multiplum.",
    explanation: "math.gcd er nyttig når en brøk skal forkortes eller grupper skal deles likt. math.lcm finner det første positive tallet som begge tallene går opp i.",
    example: "import math\n\nprint(\"SFD:\", math.gcd(18, 24))\nprint(\"MFM:\", math.lcm(6, 8))",
    result: "SFD: 6\nMFM: 24",
    keywords: ["største felles divisor", "sfd", "minste felles multiplum", "mfm", "faktor", "delelig", "gcd", "lcm"],
  },
  {
    id: "math-hypot",
    category: "Tall og statistikk",
    syntax: "math.hypot(a, b)",
    title: "hypot finner hypotenusen",
    summary: "hypot regner ut kvadratroten av a² + b².",
    explanation: "Kommandoen bruker Pytagoras og passer når a og b er katetene i en rettvinklet trekant. Den er en kortform for math.sqrt(a ** 2 + b ** 2).",
    example: "import math\n\na = 3\nb = 4\nprint(math.hypot(a, b))",
    result: "5.0",
    keywords: ["hypotenus", "pythagoras", "rettvinklet trekant", "katet", "hypot", "avstand"],
  },
  {
    id: "math-trig",
    category: "Tall og statistikk",
    syntax: "math.sin(vinkel) / cos / tan",
    title: "sin, cos og tan regner med vinkler",
    summary: "De trigonometriske funksjonene bruker en vinkel målt i radianer.",
    explanation: "Skoleoppgaver bruker ofte grader. Gjør derfor om med math.radians(grader) før du bruker sin, cos eller tan. Resultatet er et forholdstall mellom sider.",
    example: "import math\n\ngrader = 30\nvinkel = math.radians(grader)\nprint(round(math.sin(vinkel), 3))",
    result: "0.5",
    commonMistake: "math.sin(30) tolker 30 som radianer. Bruk math.sin(math.radians(30)).",
    keywords: ["sinus", "cosinus", "tangens", "sin", "cos", "tan", "vinkel", "trigonometri"],
  },
  {
    id: "math-inverse-trig",
    category: "Tall og statistikk",
    syntax: "math.degrees(math.asin(forhold))",
    title: "asin, acos og atan finner vinkler",
    summary: "De omvendte trigonometriske funksjonene finner en vinkel fra et sideforhold.",
    explanation: "asin, acos og atan gir svaret i radianer. Pakk derfor resultatet inn i math.degrees(...) hvis vinkelen skal vises i grader.",
    example: "import math\n\nforhold = 6 / 10\nvinkel = math.degrees(math.asin(forhold))\nprint(round(vinkel, 1), \"grader\")",
    result: "36.9 grader",
    keywords: ["finn vinkel", "omvendt sinus", "arcsin", "asin", "acos", "atan", "grader"],
  },
  {
    id: "math-log",
    category: "Tall og statistikk",
    syntax: "math.log(tall, grunntall) / math.log10(tall)",
    title: "log finner eksponenten",
    summary: "En logaritme svarer på hvilken eksponent et grunntall må ha.",
    explanation: "math.log(8, 2) blir 3 fordi 2 ** 3 = 8. math.log10(1000) blir 3. Uten et grunntall bruker math.log det naturlige grunntallet e.",
    example: "import math\n\nprint(math.log(8, 2))\nprint(math.log10(1000))",
    result: "3.0\n3.0",
    keywords: ["logaritme", "log", "log10", "eksponent", "grunntall", "vekst"],
  },
  {
    id: "math-factorial-comb",
    category: "Tall og statistikk",
    syntax: "math.factorial(n) / math.comb(n, k)",
    title: "factorial og comb teller muligheter",
    summary: "factorial regner n!, og comb teller valg uten rekkefølge.",
    explanation: "5! betyr 5 · 4 · 3 · 2 · 1. math.comb(10, 3) teller hvor mange måter tre kan velges fra ti når rekkefølgen ikke betyr noe.",
    example: "import math\n\nprint(\"5! =\", math.factorial(5))\nprint(\"Velg 3 av 10:\", math.comb(10, 3))",
    result: "5! = 120\nVelg 3 av 10: 120",
    keywords: ["fakultet", "factorial", "kombinasjoner", "comb", "antall muligheter", "sannsynlighet"],
  },
  {
    id: "statistics-multimode",
    category: "Tall og statistikk",
    syntax: "statistics.multimode(verdier)",
    title: "multimode finner alle typetall",
    summary: "multimode gir en liste med alle verdiene som forekommer oftest.",
    explanation: "Bruk multimode når datasettet kan ha mer enn ett typetall. Resultatet er alltid en liste, også når det bare finnes ett typetall.",
    example: "import statistics\n\ntall = [1, 1, 2, 2, 3]\nprint(statistics.multimode(tall))",
    result: "[1, 2]",
    keywords: ["flere typetall", "typetall", "mest vanlig", "multimode", "frekvens"],
  },
  {
    id: "statistics-stdev",
    category: "Tall og statistikk",
    syntax: "statistics.pstdev(tall) / statistics.stdev(tall)",
    title: "pstdev og stdev finner standardavvik",
    summary: "Standardavvik beskriver hvor langt verdiene typisk ligger fra gjennomsnittet.",
    explanation: "Bruk pstdev når listen er hele gruppen som undersøkes. Bruk stdev når tallene er et utvalg fra en større gruppe. Et stort standardavvik betyr stor spredning.",
    example: "import statistics\n\ntall = [4, 5, 6, 7, 8]\nprint(round(statistics.pstdev(tall), 2))",
    result: "1.41",
    keywords: ["standardavvik", "spredning", "pstdev", "stdev", "avstand fra gjennomsnitt", "variasjon"],
  },
  {
    id: "statistics-variance",
    category: "Tall og statistikk",
    syntax: "statistics.pvariance(tall) / statistics.variance(tall)",
    title: "variance finner variansen",
    summary: "Varians er gjennomsnittlig kvadrert avvik fra gjennomsnittet.",
    explanation: "pvariance brukes for hele datasettet, variance for et utvalg. Standardavviket er kvadratroten av variansen og er ofte lettere å tolke fordi det har samme enhet som dataene.",
    example: "import statistics\n\ntall = [2, 4, 6, 8]\nprint(statistics.pvariance(tall))",
    result: "5",
    keywords: ["varians", "variance", "pvariance", "spredning", "kvadrert avvik"],
  },
  {
    id: "statistics-quantiles",
    category: "Tall og statistikk",
    syntax: "statistics.quantiles(tall, n=4)",
    title: "quantiles finner kvartilgrenser",
    summary: "Med n=4 deles de sorterte dataene i fire deler.",
    explanation: "Resultatet inneholder tre grenser: nedre kvartil, medianområdet og øvre kvartil. Det finnes flere avtalte beregningsmetoder for små datasett, så svar kan avvike fra enkelte lærebøker.",
    example: "import statistics\n\ntall = [3, 5, 6, 7, 8, 10, 12, 14]\nprint(statistics.quantiles(tall, n=4))",
    keywords: ["kvartil", "kvartiler", "quantiles", "nedre kvartil", "øvre kvartil", "boksplott", "prosentil"],
  },
  {
    id: "fraction",
    category: "Tall og statistikk",
    syntax: "Fraction(teller, nevner)",
    title: "Fraction regner med eksakte brøker",
    summary: "Fraction beholder et svar som brøk og forkorter automatisk.",
    explanation: "Importer Fraction fra fractions. Dette unngår at en tredel tidlig blir et avrundet desimaltall. Brøken kan senere gjøres om med float hvis ønskelig.",
    example: "from fractions import Fraction\n\nsvar = Fraction(1, 3) + Fraction(1, 6)\nprint(svar)\nprint(float(svar))",
    result: "1/2\n0.5",
    keywords: ["brøk", "eksakt", "teller", "nevner", "fraction", "forkorte brøk"],
  },
  {
    id: "decimal",
    category: "Tall og statistikk",
    syntax: "Decimal(\"19.90\")",
    title: "Decimal regner nøyaktig med desimaler",
    summary: "Decimal er nyttig når bestemte desimaler må bevares, for eksempel penger.",
    explanation: "Importer Decimal fra decimal og lag verdien fra tekst. Da unngår du de små binære avrundingsforskjellene som float kan gi.",
    example: "from decimal import Decimal\n\npris = Decimal(\"19.90\")\nprint(pris * 3)",
    result: "59.70",
    commonMistake: "Bruk Decimal(\"0.1\") med tekst, ikke Decimal(0.1), hvis du vil ha nøyaktig 0.1.",
    keywords: ["penger", "nøyaktig desimal", "decimal", "avrundingsfeil", "valuta"],
  },
  {
    id: "random-sample",
    category: "Tall og statistikk",
    syntax: "random.sample(samling, antall)",
    title: "sample trekker flere uten tilbakelegging",
    summary: "sample velger et bestemt antall forskjellige elementer.",
    explanation: "Importer random. Hvert element kan bare bli valgt én gang i samme trekk. Bruk choices hvis samme element skal kunne trekkes flere ganger.",
    example: "import random\n\ntall = list(range(1, 11))\nprint(random.sample(tall, 3))",
    keywords: ["tilfeldig utvalg", "trekk flere", "uten tilbakelegging", "sample", "lotteri"],
  },
  {
    id: "random-uniform",
    category: "Tall og statistikk",
    syntax: "random.uniform(min, maks)",
    title: "uniform trekker et tilfeldig desimaltall",
    summary: "uniform gir et tilfeldig float-tall mellom to grenser.",
    explanation: "Kommandoen passer til simuleringer med kontinuerlige verdier, for eksempel en tilfeldig lengde eller tid. Bruk randint når du trenger heltall.",
    example: "import random\n\nlengde = random.uniform(5, 10)\nprint(round(lengde, 2))",
    keywords: ["tilfeldig desimaltall", "uniform", "random float", "simulering", "mellom to tall"],
  },
  {
    id: "numpy-arange",
    category: "Tall og statistikk",
    syntax: "np.arange(start, stopp, steg)",
    title: "arange lager en tallserie med fast steg",
    summary: "arange ligner range, men lager et NumPy-array og kan bruke desimalsteg.",
    explanation: "Stoppverdien er vanligvis ikke med. Bruk linspace når endepunktene er viktigere enn steglengden.",
    example: "import numpy as np\n\nx = np.arange(0, 5, 0.5)\nprint(x)",
    keywords: ["numpy tallserie", "arange", "desimalsteg", "intervall", "x verdier", "range numpy"],
  },
  {
    id: "numpy-statistics",
    category: "Tall og statistikk",
    syntax: "np.mean / np.median / np.std",
    title: "NumPy finner statistikk for arrays",
    summary: "NumPy kan finne sentralmål og spredning i en hel tallserie.",
    explanation: "np.mean finner gjennomsnitt, np.median median, og np.std standardavvik for hele datasettet. np.sum, np.min og np.max virker på samme måte.",
    example: "import numpy as np\n\ntall = np.array([4, 7, 9, 6, 10])\nprint(np.mean(tall))\nprint(np.median(tall))\nprint(round(np.std(tall), 2))",
    keywords: ["numpy gjennomsnitt", "numpy median", "numpy standardavvik", "np mean", "np std", "statistikk array"],
  },
  {
    id: "numpy-percentile",
    category: "Tall og statistikk",
    syntax: "np.percentile(tall, prosent)",
    title: "percentile finner en prosentil",
    summary: "En prosentil er en verdi som en bestemt andel av dataene ligger under.",
    explanation: "25-, 50- og 75-prosentilen brukes ofte som nedre kvartil, median og øvre kvartil. For små datasett finnes flere beregningsmetoder.",
    example: "import numpy as np\n\ntall = np.array([2, 4, 6, 8, 10])\nprint(np.percentile(tall, [25, 50, 75]))",
    keywords: ["prosentil", "percentile", "kvartil", "numpy kvartiler", "25 prosent", "75 prosent"],
  },
  {
    id: "pandas-describe",
    category: "Filer og data",
    syntax: "tabell.describe()",
    title: "describe lager en statistisk oversikt",
    summary: "describe viser antall, gjennomsnitt, standardavvik, kvartiler og ytterverdier.",
    explanation: "Kommandoen arbeider vanligvis med alle tallkolonnene i en DataFrame. Bruk print(tabell.describe()) for å vise oversikten.",
    example: "import pandas as pd\n\ntabell = pd.DataFrame({\"poeng\": [4, 7, 9, 6, 10]})\nprint(tabell.describe())",
    keywords: ["pandas statistikk", "describe", "tabell oversikt", "kvartiler", "gjennomsnitt dataframe"],
  },
  {
    id: "pandas-filter",
    category: "Filer og data",
    syntax: "tabell[tabell[\"kolonne\"] >= verdi]",
    title: "et vilkår filtrerer DataFrame-rader",
    summary: "Bare radene der sammenligningen er sann, blir beholdt.",
    explanation: "Den indre delen lager True eller False for hver rad. De ytre hakeparentesene bruker svarene til å velge radene.",
    example: "import pandas as pd\n\ntabell = pd.DataFrame({\"navn\": [\"Ada\", \"Bo\"], \"poeng\": [8, 12]})\nprint(tabell[tabell[\"poeng\"] >= 10])",
    keywords: ["filtrer tabell", "velg rader", "pandas vilkår", "dataframe filter", "større enn kolonne"],
  },
  {
    id: "pandas-groupby",
    category: "Filer og data",
    syntax: "tabell.groupby(\"gruppe\")[\"tall\"].mean()",
    title: "groupby regner for hver gruppe",
    summary: "groupby deler radene i grupper før en beregning gjøres.",
    explanation: "Dette passer når du vil finne for eksempel gjennomsnitt per klasse, lag eller måned. Velg gruppekolonne, tallkolonne og ønsket beregning.",
    example: "import pandas as pd\n\ntabell = pd.DataFrame({\"klasse\": [\"A\", \"A\", \"B\"], \"poeng\": [8, 12, 9]})\nprint(tabell.groupby(\"klasse\")[\"poeng\"].mean())",
    keywords: ["grupper data", "groupby", "gjennomsnitt per gruppe", "pandas gruppe", "klassevis"],
  },
  {
    id: "sympy-solve",
    category: "Tall og statistikk",
    syntax: "sp.solve(sp.Eq(venstre, høyre), x)",
    title: "SymPy solve løser en ligning",
    summary: "solve finner verdier av symbolet som gjør ligningen sann.",
    explanation: "Importer sympy as sp, lag x med sp.symbols og bruk sp.Eq for likhetstegnet i ligningen. Resultatet er en liste fordi en ligning kan ha flere løsninger.",
    example: "import sympy as sp\n\nx = sp.symbols(\"x\")\nligning = sp.Eq(3 * x - 5, 16)\nprint(sp.solve(ligning, x))",
    result: "[7]",
    keywords: ["løs ligning", "sympy solve", "algebra", "finn x", "equation", "sp eq"],
  },
  {
    id: "sympy-expand-factor",
    category: "Tall og statistikk",
    syntax: "sp.expand(uttrykk) / sp.factor(uttrykk)",
    title: "expand ganger ut og factor faktoriserer",
    summary: "Kommandoene viser to forskjellige former av det samme algebraiske uttrykket.",
    explanation: "expand fjerner parenteser ved å gange ut. factor går motsatt vei når uttrykket kan faktoriseres. Bruk dem til å undersøke og kontrollere algebra.",
    example: "import sympy as sp\n\nx = sp.symbols(\"x\")\nuttrykk = (x + 2) * (x - 3)\nprint(sp.expand(uttrykk))\nprint(sp.factor(sp.expand(uttrykk)))",
    keywords: ["gang ut parentes", "faktoriser", "sympy expand", "sympy factor", "algebraisk uttrykk"],
  },
  {
    id: "scipy-linregress",
    category: "Tall og statistikk",
    syntax: "stats.linregress(x, y)",
    title: "linregress finner en lineær modell",
    summary: "SciPy finner stigningstall, konstantledd og hvor godt en linje passer.",
    explanation: "Importer stats fra scipy. slope er a og intercept er b i y = ax + b. rvalue ** 2 gir R². x og y må ha like mange verdier.",
    example: "from scipy import stats\n\nx = [1, 2, 3, 4]\ny = [3, 5, 7, 9]\nmodell = stats.linregress(x, y)\nprint(modell.slope, modell.intercept)",
    result: "2.0 1.0",
    keywords: ["lineær regresjon", "linregress", "stigningstall", "konstantledd", "r i andre", "trendlinje", "scipy"],
  },
  {
    id: "scipy-binom",
    category: "Tall og statistikk",
    syntax: "stats.binom.pmf(k, n, p)",
    title: "binom.pmf finner binomisk sannsynlighet",
    summary: "Kommandoen finner sannsynligheten for nøyaktig k treff i n uavhengige forsøk.",
    explanation: "p er sannsynligheten for treff i hvert forsøk. Modellen krever fast antall forsøk, to mulige utfall, lik p og uavhengige forsøk.",
    example: "from scipy import stats\n\nsannsynlighet = stats.binom.pmf(2, 5, 0.5)\nprint(round(sannsynlighet, 4))",
    result: "0.3125",
    keywords: ["binomisk", "sannsynlighet", "nøyaktig treff", "binom pmf", "scipy stats", "forsøk"],
  },
  {
    id: "scipy-root",
    category: "Tall og statistikk",
    syntax: "root_scalar(f, bracket=[min, maks])",
    title: "root_scalar finner et nullpunkt numerisk",
    summary: "SciPy leter etter en x-verdi der funksjonen er omtrent 0.",
    explanation: "Oppgi en funksjon og et intervall der funksjonen skifter fortegn. result.root er nullpunktet. Dette gir en tilnærmet desimalløsning.",
    example: "from scipy.optimize import root_scalar\n\ndef f(x):\n    return x ** 2 - 2\n\nsvar = root_scalar(f, bracket=[1, 2])\nprint(round(svar.root, 6))",
    result: "1.414214",
    keywords: ["nullpunkt", "løs ligning numerisk", "root scalar", "scipy optimize", "skjæring x aksen"],
  },
  {
    id: "sklearn-linear-regression",
    category: "Tall og statistikk",
    syntax: "LinearRegression().fit(x, y)",
    title: "LinearRegression lager en lineær modell",
    summary: "scikit-learn kan tilpasse og bruke en modell for y fra én eller flere variabler.",
    explanation: "x må være en tabell med én rad per eksempel, mens y er svarverdiene. Bruk modellen kritisk: et godt mønster betyr ikke automatisk årsakssammenheng.",
    example: "import numpy as np\nfrom sklearn.linear_model import LinearRegression\n\nx = np.array([[1], [2], [3], [4]])\ny = np.array([3, 5, 7, 9])\nmodell = LinearRegression().fit(x, y)\nprint(modell.predict([[5]])[0])",
    result: "11.0",
    keywords: ["maskinlæring", "linear regression", "sklearn", "anslag", "prediksjon", "modell", "regresjon"],
  },
  {
    id: "plt-hist",
    category: "Tegning",
    syntax: "plt.hist(tall, bins=antall)",
    title: "hist tegner et histogram",
    summary: "Et histogram grupperer tall i intervaller og viser frekvensen.",
    explanation: "bins bestemmer hvor mange intervaller som brukes. Histogram passer kontinuerlige eller mange numeriske data; stolpediagram passer kategorier.",
    example: "import matplotlib.pyplot as plt\n\ntall = [2, 3, 3, 4, 5, 5, 5, 7, 8, 9]\nplt.hist(tall, bins=4, edgecolor=\"black\")\nplt.xlabel(\"Verdi\")\nplt.ylabel(\"Frekvens\")\nplt.show()",
    keywords: ["histogram", "frekvens", "intervall", "fordeling", "bins", "matplotlib"],
  },
  {
    id: "shapely-measures",
    category: "Tall og statistikk",
    syntax: "figur.area / figur.length / figur.distance(annen)",
    title: "Shapely måler geometriske figurer",
    summary: "Geometriobjekter kan gi areal, omkrets og avstand direkte.",
    explanation: "Lag figuren fra koordinater. area gir flateinnhold, length gir omkrets for en Polygon, og distance finner korteste avstand mellom objekter.",
    example: "from shapely.geometry import Polygon\n\nfigur = Polygon([(0, 0), (6, 0), (6, 4), (0, 4)])\nprint(figur.area)\nprint(figur.length)",
    result: "24.0\n20.0",
    keywords: ["shapely", "areal koordinater", "omkrets polygon", "avstand figurer", "geometri"],
  },
  {
    id: "networkx-shortest-path",
    category: "Tall og statistikk",
    syntax: "nx.shortest_path(graf, start, slutt, weight=\"vekt\")",
    title: "NetworkX finner korteste rute",
    summary: "Nettverket kan finne en rute med færrest forbindelser eller lavest total vekt.",
    explanation: "Uten weight telles antall kanter. Med weight summeres for eksempel avstander eller tider som er lagret på forbindelsene.",
    example: "import networkx as nx\n\ngraf = nx.Graph()\ngraf.add_edge(\"A\", \"B\", vekt=4)\ngraf.add_edge(\"B\", \"C\", vekt=2)\ngraf.add_edge(\"A\", \"C\", vekt=9)\nprint(nx.shortest_path(graf, \"A\", \"C\", weight=\"vekt\"))",
    result: "['A', 'B', 'C']",
    keywords: ["networkx", "korteste vei", "korteste rute", "nettverk", "grafteori", "vektet graf"],
  },
];
