import { mathLibraryCommands } from "./mathCommands.ts";

export const commandCategories = [
  "Alle",
  "Grunnleggende",
  "Regning",
  "Sammenligning",
  "Tekst",
  "Lister og samlinger",
  "Valg og løkker",
  "Funksjoner",
  "Tall og statistikk",
  "Filer og data",
  "Tegning",
  "Feil og kontroll",
] as const;

export type CommandCategory = (typeof commandCategories)[number];

export type PythonCommand = {
  id: string;
  category: Exclude<CommandCategory, "Alle">;
  syntax: string;
  title: string;
  summary: string;
  explanation: string;
  example: string;
  result?: string;
  commonMistake?: string;
  keywords: string[];
};

// Forklaringene er med vilje skrevet som et oppslagsverk for helt ferske kodere.
// Søkeordene inneholder både Python-navn og vanlige norske formuleringer.
export const pythonCommands: PythonCommand[] = [
  {
    id: "assign",
    category: "Grunnleggende",
    syntax: "navn = verdi",
    title: "= gir en verdi til en variabel",
    summary: "Likhetstegnet lagrer verdien på høyre side under navnet på venstre side.",
    explanation: "Python regner ut høyresiden først. Deretter får variabelen på venstre side denne verdien. Les pris = 80 som «pris får verdien 80». Dette er tildeling, ikke et spørsmål om to sider er like.",
    example: "pris = 80\nantall = 3\ntotal = pris * antall\nprint(total)",
    result: "240",
    commonMistake: "Bruk ==, ikke =, når du vil undersøke om to verdier er like.",
    keywords: ["er lik", "sett verdi", "lagre", "variabel", "tildeling", "tilordning", "får verdien", "likhetstegn"],
  },
  {
    id: "comment",
    category: "Grunnleggende",
    syntax: "# kommentar",
    title: "# skriver en kommentar",
    summary: "En kommentar forklarer koden til mennesker og blir hoppet over av Python.",
    explanation: "Alt etter # på samme linje er en beskjed til den som leser. Bruk kommentarer til å forklare hvorfor programmet gjør noe, eller hva eleven skal endre.",
    example: "# Pris før rabatt\npris = 800\nprint(pris)",
    result: "800",
    commonMistake: "Python bruker # til kommentarer. // er ikke et kommentartegn i Python.",
    keywords: ["forklaring i kode", "merknad", "notat", "hashtag", "kommentar", "ignorere linje"],
  },
  {
    id: "print",
    category: "Grunnleggende",
    syntax: "print(...) ",
    title: "print viser et svar",
    summary: "print viser tekst, verdier eller resultater i resultatfeltet.",
    explanation: "Legg det du vil vise mellom parentesene. Flere deler kan skilles med komma. Tekst må ha anførselstegn, mens variabler og regnestykker skal stå uten.",
    example: "navn = \"Ada\"\npoeng = 7\nprint(\"Hei\", navn, \"– du fikk\", poeng + 2, \"poeng.\")",
    result: "Hei Ada – du fikk 9 poeng.",
    commonMistake: "print(\"poeng + 2\") viser selve teksten. Fjern anførselstegnene hvis Python skal regne.",
    keywords: ["skriv ut", "vis", "resultat", "svar", "tekst og tall", "utskrift", "konsoll"],
  },
  {
    id: "input",
    category: "Grunnleggende",
    syntax: "input(\"Spørsmål: \")",
    title: "input spør brukeren",
    summary: "input stopper programmet og venter på at brukeren skriver et svar.",
    explanation: "Når koden kjøres, åpner Skolepython et svarvindu med teksten du skrev i input. Svaret fra input blir alltid tekst. Hvis du trenger et tall, må teksten gjøres om med int eller float.",
    example: "alder_tekst = input(\"Hvor gammel er du? \")\nalder = int(alder_tekst)\nprint(\"Neste år er du\", alder + 1, \"år.\")",
    result: "Skriver brukeren 14, blir svaret: Neste år er du 15 år.",
    commonMistake: "Uten int blir alder tekst. Da gir alder + 1 TypeError, fordi Python ikke kan legge sammen tekst og et tall.",
    keywords: ["spør", "prompt", "bruker skriver", "les inn", "inndata", "tastatur", "svar fra bruker", "interaktiv"],
  },
  {
    id: "type",
    category: "Grunnleggende",
    syntax: "type(verdi)",
    title: "type undersøker datatypen",
    summary: "type forteller om en verdi er for eksempel tekst, heltall, desimaltall eller liste.",
    explanation: "Datatypen bestemmer hva Python kan gjøre med verdien. Det er nyttig å skrive print(type(verdi)) når tekst og tall ikke oppfører seg som forventet.",
    example: "alder = 15\nnavn = \"Ada\"\nprint(type(alder))\nprint(type(navn))",
    result: "<class 'int'>\n<class 'str'>",
    keywords: ["datatype", "hvilken type", "int", "str", "float", "undersøk verdi"],
  },
  {
    id: "int",
    category: "Grunnleggende",
    syntax: "int(verdi)",
    title: "int gjør om til heltall",
    summary: "int gjør en passende tekst eller et desimaltall om til et heltall.",
    explanation: "int(\"15\") blir tallet 15. int(3.9) blir 3 fordi desimaldelen kuttes bort; det er ikke vanlig avrunding.",
    example: "tekst = \"15\"\nalder = int(tekst)\nprint(alder + 1)",
    result: "16",
    commonMistake: "int(\"3,5\") virker ikke. Desimaltall trenger punktum og float, for eksempel float(\"3.5\").",
    keywords: ["heltall", "gjør tekst til tall", "konverter", "integer", "uten desimal"],
  },
  {
    id: "float",
    category: "Grunnleggende",
    syntax: "float(verdi)",
    title: "float gjør om til desimaltall",
    summary: "float gjør en passende tekst eller et heltall om til et desimaltall.",
    explanation: "Python bruker punktum som desimalskilletegn. Når norske data har komma, kan teksten først endres med replace.",
    example: "tekst = \"12,5\"\ntall = float(tekst.replace(\",\", \".\"))\nprint(tall * 2)",
    result: "25.0",
    commonMistake: "float(\"12,5\") gir feil fordi Python forventer 12.5.",
    keywords: ["desimaltall", "kommatall", "gjør tekst til tall", "konverter", "decimal"],
  },
  {
    id: "str",
    category: "Grunnleggende",
    syntax: "str(verdi)",
    title: "str gjør om til tekst",
    summary: "str lager en tekstutgave av en verdi.",
    explanation: "Dette trengs blant annet når tekst skal settes sammen med +. Med komma i print eller en f-tekst slipper du ofte å bruke str selv.",
    example: "alder = 15\nmelding = \"Jeg er \" + str(alder) + \" år.\"\nprint(melding)",
    result: "Jeg er 15 år.",
    keywords: ["string", "tekst", "gjør tall til tekst", "konverter", "sette sammen"],
  },
  {
    id: "bool",
    category: "Grunnleggende",
    syntax: "True / False",
    title: "True og False betyr sant og usant",
    summary: "Sammenligninger og vilkår gir én av de to boolske verdiene True eller False.",
    explanation: "Python bruker stor forbokstav i True og False. Verdiene kan lagres i variabler og brukes direkte i if.",
    example: "har_billett = True\nif har_billett:\n    print(\"Du kan gå inn.\")",
    result: "Du kan gå inn.",
    commonMistake: "true og false med liten forbokstav er ikke Python-navn.",
    keywords: ["sant", "usant", "boolean", "boolsk", "ja nei", "vilkår"],
  },

  {
    id: "plus",
    category: "Regning",
    syntax: "a + b",
    title: "+ legger sammen",
    summary: "Plusstegnet summerer tall eller setter tekst og lister sammen.",
    explanation: "Med tall betyr + addisjon. Med to tekster betyr + at tekstene skjøtes sammen. Datatypene på begge sider må passe sammen.",
    example: "pris = 80\nfrakt = 49\nprint(pris + frakt)",
    result: "129",
    commonMistake: "\"8\" + \"2\" blir teksten \"82\", ikke tallet 10.",
    keywords: ["pluss", "addisjon", "sum", "legg sammen", "øke", "sammenføye"],
  },
  {
    id: "minus",
    category: "Regning",
    syntax: "a - b",
    title: "- trekker fra",
    summary: "Minustegnet finner forskjellen mellom tall eller gjør et tall negativt.",
    explanation: "Python regner venstre verdi minus høyre verdi. -tall foran én verdi skifter fortegn.",
    example: "pris = 800\nrabatt = 200\nprint(pris - rabatt)",
    result: "600",
    keywords: ["minus", "subtraksjon", "trekk fra", "differanse", "forskjell", "negativ"],
  },
  {
    id: "multiply",
    category: "Regning",
    syntax: "a * b",
    title: "* ganger",
    summary: "Én stjerne betyr multiplikasjon.",
    explanation: "Python bruker * fordi gangetegnet · vanligvis ikke finnes på tastaturet. En tekst ganget med et heltall gjentas.",
    example: "pris = 75\nantall = 4\nprint(pris * antall)",
    result: "300",
    commonMistake: "Potens bruker ** med to stjerner; én stjerne er vanlig gange.",
    keywords: ["gange", "multiplisere", "multiplikasjon", "produkt", "doble"],
  },
  {
    id: "divide",
    category: "Regning",
    syntax: "a / b",
    title: "/ deler",
    summary: "Skråstreken deler venstre tall på høyre tall.",
    explanation: "Vanlig divisjon med / gir et desimaltall, også når svaret er helt. 8 / 2 blir derfor 4.0.",
    example: "sum_poeng = 24\nantall = 3\nprint(sum_poeng / antall)",
    result: "8.0",
    commonMistake: "Det er ikke mulig å dele på 0.",
    keywords: ["dele", "divisjon", "brøk", "kvotient", "gjennomsnitt"],
  },
  {
    id: "floor-divide",
    category: "Regning",
    syntax: "a // b",
    title: "// gir heltallsdivisjon",
    summary: "To skråstreker deler og runder svaret ned til et helt antall.",
    explanation: "17 // 5 blir 3 fordi fem går tre hele ganger i 17. Resten kan finnes med %.",
    example: "minutter = 137\nprint(minutter // 60, \"hele timer\")",
    result: "2 hele timer",
    commonMistake: "// betyr ikke kommentar i Python.",
    keywords: ["heltallsdivisjon", "hele ganger", "dele uten desimal", "gulvdivisjon"],
  },
  {
    id: "modulo",
    category: "Regning",
    syntax: "a % b",
    title: "% finner resten etter divisjon",
    summary: "Prosenttegnet gir divisjonsresten, ikke prosentregning.",
    explanation: "17 % 5 blir 2 fordi 17 = 3 · 5 + 2. Kommandoen er nyttig til partall, klokkeslett og mønstre som gjentar seg.",
    example: "tall = 14\nprint(tall % 2)",
    result: "0",
    commonMistake: "25 % rabatt regnes ikke med %-operatoren. Bruk for eksempel pris * 0.75.",
    keywords: ["modulo", "divisjonsrest", "rest", "partall", "oddetall", "delelig"],
  },
  {
    id: "power",
    category: "Regning",
    syntax: "a ** b",
    title: "** opphøyer i en potens",
    summary: "To stjerner betyr grunntall opphøyd i eksponenten.",
    explanation: "2 ** 3 betyr 2 · 2 · 2 og blir 8. Kvadratet av x skrives x ** 2.",
    example: "side = 5\nareal = side ** 2\nprint(areal)",
    result: "25",
    commonMistake: "^ betyr ikke potens i Python. Bruk **.",
    keywords: ["potens", "opphøyd", "eksponent", "kvadrat", "andre", "kubikk"],
  },
  {
    id: "parentheses",
    category: "Regning",
    syntax: "(uttrykk)",
    title: "Parentes bestemmer regnerekkefølgen",
    summary: "Det som står i parentes, regnes ut før det som står utenfor.",
    explanation: "Python følger vanlige regneregler. Bruk parenteser både for å få riktig rekkefølge og for å gjøre tankegangen tydelig.",
    example: "pris = 800\nrabatt = 0.25\nny_pris = pris * (1 - rabatt)\nprint(ny_pris)",
    result: "600.0",
    keywords: ["regnerekkefølge", "parentes", "først", "rekkefølge", "prioritet"],
  },
  {
    id: "plus-equals",
    category: "Regning",
    syntax: "verdi += tillegg",
    title: "+= øker og lagrer",
    summary: "+= legger noe til den gamle verdien og lagrer den nye verdien i samme variabel.",
    explanation: "poeng += 3 er en kortere måte å skrive poeng = poeng + 3 på. Først hentes den gamle verdien, så legges 3 til.",
    example: "poeng = 5\npoeng += 3\nprint(poeng)",
    result: "8",
    keywords: ["øk", "øke variabel", "legg til", "pluss er lik", "oppdater verdi", "telle opp"],
  },
  {
    id: "minus-equals",
    category: "Regning",
    syntax: "verdi -= fratrekk",
    title: "-= minker og lagrer",
    summary: "-= trekker fra den gamle verdien og lagrer den nye verdien.",
    explanation: "liv -= 1 betyr det samme som liv = liv - 1. Det brukes ofte i spill, nedtelling og beholdninger.",
    example: "liv = 3\nliv -= 1\nprint(liv)",
    result: "2",
    keywords: ["mink", "trekk fra variabel", "minus er lik", "reduser", "oppdater verdi", "telle ned"],
  },
  {
    id: "multiply-equals",
    category: "Regning",
    syntax: "verdi *= faktor",
    title: "*= ganger og lagrer",
    summary: "*= ganger den gamle verdien med en faktor og lagrer svaret.",
    explanation: "belop *= 1.10 betyr belop = belop * 1.10. Det passer når samme vekstfaktor brukes flere ganger.",
    example: "belop = 1000\nbelop *= 1.10\nprint(belop)",
    result: "1100.0",
    keywords: ["gang variabel", "gange er lik", "vekstfaktor", "oppdater verdi", "prosentøkning"],
  },
  {
    id: "divide-equals",
    category: "Regning",
    syntax: "verdi /= divisor",
    title: "/= deler og lagrer",
    summary: "/= deler den gamle verdien og lagrer svaret.",
    explanation: "mengde /= 2 betyr mengde = mengde / 2. Resultatet blir vanligvis et desimaltall.",
    example: "mengde = 10\nmengde /= 2\nprint(mengde)",
    result: "5.0",
    keywords: ["del variabel", "dele er lik", "halvere", "oppdater verdi"],
  },
  {
    id: "round",
    category: "Regning",
    syntax: "round(tall, desimaler)",
    title: "round avrunder et tall",
    summary: "round lager en avrundet tallverdi med ønsket antall desimaler.",
    explanation: "round(3.14159, 2) blir 3.14. Dette endrer verdien som brukes videre, mens :.2f i en f-tekst bare bestemmer hvordan tallet vises.",
    example: "pris = 199 / 3\nprint(round(pris, 2))",
    result: "66.33",
    keywords: ["avrund", "desimaler", "to desimaler", "nærmeste", "pene tall"],
  },
  {
    id: "abs",
    category: "Regning",
    syntax: "abs(tall)",
    title: "abs finner absoluttverdien",
    summary: "abs gir avstanden fra 0, uten negativt fortegn.",
    explanation: "abs(-7) og abs(7) blir begge 7. Det er nyttig når du vil finne avstanden eller forskjellen uansett retning.",
    example: "forskjell = abs(12 - 20)\nprint(forskjell)",
    result: "8",
    keywords: ["absoluttverdi", "avstand fra null", "positiv forskjell", "uten minus"],
  },

  {
    id: "equal",
    category: "Sammenligning",
    syntax: "a == b",
    title: "== undersøker om to verdier er like",
    summary: "To likhetstegn stiller spørsmålet «er disse like?» og gir True eller False.",
    explanation: "Det første likhetstegnet er del av sammenligningstegnet, ikke en tildeling. 5 == 5 blir True, mens 5 == 6 blir False.",
    example: "svar = 10\nprint(svar == 10)",
    result: "True",
    commonMistake: "Ett likhetstegn (=) gir en verdi. To (==) sammenligner.",
    keywords: ["er lik", "samme som", "sammenlign", "lik verdi", "to likhetstegn", "likhet"],
  },
  {
    id: "not-equal",
    category: "Sammenligning",
    syntax: "a != b",
    title: "!= undersøker om verdier er ulike",
    summary: "Utropstegn og likhetstegn betyr «er ikke lik».",
    explanation: "5 != 6 blir True fordi tallene er forskjellige. Sammenligningen blir False hvis verdiene er like.",
    example: "passord = \"python\"\nprint(passord != \"kode\")",
    result: "True",
    keywords: ["ikke lik", "ulik", "forskjellig", "er ikke", "sammenlign", "utropstegn"],
  },
  {
    id: "greater",
    category: "Sammenligning",
    syntax: "a > b",
    title: "> betyr større enn",
    summary: "Sammenligningen er sann når verdien til venstre er større enn verdien til høyre.",
    explanation: "8 > 5 blir True. Tegnet peker mot den minste verdien, mens den åpne siden vender mot den største.",
    example: "alder = 15\nprint(alder > 12)",
    result: "True",
    commonMistake: "Likhet er ikke med. 5 > 5 blir False.",
    keywords: ["større enn", "mer enn", "over", "høyere", "sammenligne tall"],
  },
  {
    id: "greater-equal",
    category: "Sammenligning",
    syntax: "a >= b",
    title: ">= betyr større enn eller lik",
    summary: "Sammenligningen er sann når venstre verdi er større enn eller nøyaktig lik høyre verdi.",
    explanation: "poeng >= 5 inkluderer både 5 og alle tall over 5. Tenk «minst 5».",
    example: "poeng = 5\nprint(poeng >= 5)",
    result: "True",
    commonMistake: "Skriv >= i denne rekkefølgen. => er ikke et Python-tegn.",
    keywords: ["større enn", "større eller lik", "minst", "minimum", "fra og med", "over eller lik", "nok"],
  },
  {
    id: "less",
    category: "Sammenligning",
    syntax: "a < b",
    title: "< betyr mindre enn",
    summary: "Sammenligningen er sann når venstre verdi er mindre enn høyre verdi.",
    explanation: "3 < 10 blir True. Tegnet peker mot den minste verdien.",
    example: "temperatur = -4\nprint(temperatur < 0)",
    result: "True",
    commonMistake: "Likhet er ikke med. 5 < 5 blir False.",
    keywords: ["mindre enn", "lavere", "under", "færre enn", "sammenligne tall"],
  },
  {
    id: "less-equal",
    category: "Sammenligning",
    syntax: "a <= b",
    title: "<= betyr mindre enn eller lik",
    summary: "Sammenligningen er sann når venstre verdi er mindre enn eller nøyaktig lik høyre verdi.",
    explanation: "alder <= 15 inkluderer både 15 og alle tall under 15. Tenk «høyst 15».",
    example: "alder = 15\nprint(alder <= 15)",
    result: "True",
    commonMistake: "Skriv <= i denne rekkefølgen. =< er ikke et Python-tegn.",
    keywords: ["mindre enn", "mindre eller lik", "maks", "maksimum", "høyst", "til og med", "under eller lik"],
  },
  {
    id: "and",
    category: "Sammenligning",
    syntax: "vilkår1 and vilkår2",
    title: "and krever at begge vilkårene er sanne",
    summary: "and kombinerer spørsmål og gir True bare når begge svarene er True.",
    explanation: "Bruk and når alle krav må oppfylles samtidig. 12 <= alder and alder <= 15 spør om alderen ligger fra 12 til 15.",
    example: "alder = 14\nprint(alder >= 12 and alder <= 15)",
    result: "True",
    keywords: ["og", "begge", "flere vilkår", "samtidig", "mellom", "alle krav"],
  },
  {
    id: "or",
    category: "Sammenligning",
    syntax: "vilkår1 or vilkår2",
    title: "or krever at minst ett vilkår er sant",
    summary: "or kombinerer spørsmål og gir True når ett eller begge svarene er True.",
    explanation: "Bruk or når flere forskjellige muligheter skal godtas.",
    example: "dag = \"lørdag\"\nprint(dag == \"lørdag\" or dag == \"søndag\")",
    result: "True",
    keywords: ["eller", "minst ett", "ett av", "flere muligheter", "alternativ"],
  },
  {
    id: "not",
    category: "Sammenligning",
    syntax: "not vilkår",
    title: "not snur sant og usant",
    summary: "not gjør True om til False og False om til True.",
    explanation: "not brukes når du vil undersøke at noe ikke er tilfelle. not ferdig er sant når ferdig er False.",
    example: "ferdig = False\nif not ferdig:\n    print(\"Fortsett å arbeide.\")",
    result: "Fortsett å arbeide.",
    keywords: ["ikke", "motsatt", "snur vilkår", "negasjon", "usant"],
  },
  {
    id: "in",
    category: "Sammenligning",
    syntax: "verdi in samling",
    title: "in undersøker om noe finnes i en samling",
    summary: "in gir True når verdien finnes i en tekst, liste, tuppel, mengde eller ordbok.",
    explanation: "Dette er en lesbar måte å spørre «finnes denne verdien her?» på.",
    example: "farger = [\"rød\", \"grønn\", \"blå\"]\nprint(\"grønn\" in farger)",
    result: "True",
    keywords: ["finnes i", "inneholder", "medlem", "i liste", "søk i samling"],
  },
  {
    id: "not-in",
    category: "Sammenligning",
    syntax: "verdi not in samling",
    title: "not in undersøker om noe mangler",
    summary: "not in gir True når verdien ikke finnes i samlingen.",
    explanation: "Kommandoen er det motsatte av in og er ofte lettere å lese enn not (verdi in samling).",
    example: "navn = [\"Ada\", \"Bo\"]\nprint(\"Celine\" not in navn)",
    result: "True",
    keywords: ["finnes ikke", "ikke i", "mangler", "utenfor samling"],
  },

  {
    id: "quotes",
    category: "Tekst",
    syntax: "\"tekst\" / 'tekst'",
    title: "Anførselstegn lager tekst",
    summary: "Tekst må stå mellom to like anførselstegn.",
    explanation: "Du kan bruke enten doble eller enkle anførselstegn. Velg gjerne doble som fast vane. Tall mellom anførselstegn er tekst, ikke tall det regnes med.",
    example: "skole = \"Bjørnsveen\"\nprint(skole)",
    result: "Bjørnsveen",
    commonMistake: "Hvis ett anførselstegn mangler, vet ikke Python hvor teksten slutter.",
    keywords: ["tekst", "string", "anførselstegn", "hermetegn", "sitattegn", "bokstaver"],
  },
  {
    id: "f-string",
    category: "Tekst",
    syntax: "f\"tekst {verdi}\"",
    title: "f-tekst setter verdier inn i en setning",
    summary: "Bokstaven f lar Python erstatte innhold i krøllparenteser med verdier.",
    explanation: "Skriv f rett foran anførselstegnet. Inne i { } kan du bruke variabler og regnestykker. Dette er ofte den ryddigste måten å lage et forståelig svar på.",
    example: "navn = \"Ada\"\npoeng = 7\nprint(f\"{navn} fikk {poeng + 2} poeng.\")",
    result: "Ada fikk 9 poeng.",
    commonMistake: "Uten f foran teksten blir {navn} skrevet bokstavelig.",
    keywords: ["f string", "formatert tekst", "tekst og variabel", "tekst og tall", "krøllparentes", "setning", "pene svar"],
  },
  {
    id: "format-decimals",
    category: "Tekst",
    syntax: "f\"{tall:.2f}\"",
    title: ":.2f viser to desimaler",
    summary: "Formatkoden bestemmer hvor mange desimaler et tall skal vises med.",
    explanation: "Tallet etter punktum er antall desimaler. :.0f viser ingen, :.1f viser én og :.2f viser to. Selve tallverdien i variabelen endres ikke.",
    example: "pris = 600.0\nprint(f\"Den nye prisen er {pris:.0f} kr.\")",
    result: "Den nye prisen er 600 kr.",
    keywords: ["desimaler", "formatering", "uten desimal", "to desimaler", "kr", "pene tall", "f tekst"],
  },
  {
    id: "format-percent",
    category: "Tekst",
    syntax: "f\"{andel:.1%}\"",
    title: "% i f-tekst viser en andel som prosent",
    summary: "Formatkoden ganger en andel med 100 og legger til prosenttegnet.",
    explanation: "En andel på 0.25 vises som 25.0 % med :.1%. Tallet etter punktum bestemmer antall desimaler.",
    example: "andel = 0.25\nprint(f\"Rabatt: {andel:.0%}\")",
    result: "Rabatt: 25%",
    keywords: ["prosent", "vis prosent", "andel til prosent", "format", "prosenttegn"],
  },
  {
    id: "len-text",
    category: "Tekst",
    syntax: "len(tekst)",
    title: "len teller tegn",
    summary: "len gir antall tegn i en tekst, også mellomrom.",
    explanation: "Det samme navnet len brukes også til å telle elementer i lister og andre samlinger.",
    example: "ord = \"Python\"\nprint(len(ord))",
    result: "6",
    keywords: ["lengde tekst", "antall bokstaver", "tell tegn", "hvor lang", "length"],
  },
  {
    id: "string-index",
    category: "Tekst",
    syntax: "tekst[indeks]",
    title: "[indeks] henter ett tegn",
    summary: "Hakeparentes med et tall henter tegnet på den plassen. Python teller fra 0.",
    explanation: "tekst[0] er første tegn, tekst[1] er andre, og tekst[-1] er siste tegn.",
    example: "ord = \"Python\"\nprint(ord[0], ord[-1])",
    result: "P n",
    commonMistake: "Den første plassen er 0, ikke 1.",
    keywords: ["tegn", "bokstav", "første bokstav", "siste bokstav", "indeks", "plass"],
  },
  {
    id: "slice",
    category: "Tekst",
    syntax: "verdi[start:stopp:steg]",
    title: "utvalg med : henter en del",
    summary: "Et start- og stoppnummer henter et utsnitt av tekst eller liste.",
    explanation: "Stopp-plassen er ikke med. tekst[1:4] henter plass 1, 2 og 3. Tom start betyr fra begynnelsen; tom stopp betyr til slutten.",
    example: "ord = \"Python\"\nprint(ord[0:3])\nprint(ord[::-1])",
    result: "Pyt\nnohtyP",
    keywords: ["slice", "utvalg", "del av tekst", "del av liste", "start stopp", "snu rekkefølge"],
  },
  {
    id: "lower-upper",
    category: "Tekst",
    syntax: "tekst.lower() / tekst.upper()",
    title: "lower og upper endrer små og store bokstaver",
    summary: "lower lager små bokstaver; upper lager store.",
    explanation: "Metodene lager en ny tekst. De er nyttige før sammenligning når brukeren kan ha skrevet store eller små bokstaver.",
    example: "svar = \"Ja\"\nprint(svar.lower() == \"ja\")",
    result: "True",
    keywords: ["små bokstaver", "store bokstaver", "lowercase", "uppercase", "normaliser tekst"],
  },
  {
    id: "strip",
    category: "Tekst",
    syntax: "tekst.strip()",
    title: "strip fjerner tomrom i kantene",
    summary: "strip fjerner mellomrom, tabulatorer og linjeskift før og etter teksten.",
    explanation: "Dette er særlig nyttig når linjer leses fra en fil. Innholdet midt i teksten blir ikke endret.",
    example: "tekst = \"  Ada\\n\"\nprint(tekst.strip())",
    result: "Ada",
    keywords: ["fjern mellomrom", "fjern linjeskift", "rens tekst", "whitespace", "kantene"],
  },
  {
    id: "replace",
    category: "Tekst",
    syntax: "tekst.replace(gammel, ny)",
    title: "replace bytter ut tekst",
    summary: "replace lager en ny tekst der alle treff er byttet ut.",
    explanation: "Metoden er nyttig når formater skal ryddes, for eksempel norske desimalkomma før float.",
    example: "tekst = \"12,5\"\ntall = float(tekst.replace(\",\", \".\"))\nprint(tall)",
    result: "12.5",
    keywords: ["erstatt", "bytt tekst", "endre tegn", "komma til punktum", "replace"],
  },
  {
    id: "split",
    category: "Tekst",
    syntax: "tekst.split(skilletegn)",
    title: "split deler tekst til en liste",
    summary: "split deler en tekst hver gang skilletegnet finnes.",
    explanation: "Uten argument deles teksten ved tomrom. split(\";\") deler en enkel datarad ved semikolon.",
    example: "rad = \"Ada;15;Gjøvik\"\ndeler = rad.split(\";\")\nprint(deler)",
    result: "['Ada', '15', 'Gjøvik']",
    keywords: ["del tekst", "tekst til liste", "skilletegn", "ord", "separator"],
  },
  {
    id: "join",
    category: "Tekst",
    syntax: "skilletegn.join(liste)",
    title: "join setter tekster sammen",
    summary: "join skjøter tekstverdier i en liste med ønsket skilletegn mellom.",
    explanation: "Kommandoen begynner med teksten som skal ligge mellom elementene. Alle listeverdiene må være tekst.",
    example: "ord = [\"Python\", \"er\", \"gøy\"]\nprint(\" \".join(ord))",
    result: "Python er gøy",
    keywords: ["sett sammen tekst", "liste til tekst", "skjøt", "mellomrom", "separator"],
  },

  {
    id: "list-create",
    category: "Lister og samlinger",
    syntax: "liste = [verdi1, verdi2]",
    title: "[ ] lager en liste",
    summary: "En liste samler flere verdier i en bestemt rekkefølge under ett navn.",
    explanation: "Verdiene skilles med komma. En liste kan endres etter at den er laget, og kan inneholde tall, tekst eller andre verdier.",
    example: "poeng = [4, 7, 9]\nprint(poeng)",
    result: "[4, 7, 9]",
    keywords: ["liste", "mange verdier", "samling", "hakeparentes", "array", "opprette liste"],
  },
  {
    id: "list-index",
    category: "Lister og samlinger",
    syntax: "liste[indeks]",
    title: "[indeks] henter en listeverdi",
    summary: "Indeksen er plassnummeret, og den første plassen er 0.",
    explanation: "liste[0] henter første verdi. Negative indekser teller bakfra, så liste[-1] er siste verdi.",
    example: "poeng = [4, 7, 9]\nprint(poeng[0], poeng[-1])",
    result: "4 9",
    commonMistake: "En liste med tre verdier har indeksene 0, 1 og 2 – ikke 1, 2 og 3.",
    keywords: ["hent fra liste", "første verdi", "siste verdi", "indeks", "plassnummer"],
  },
  {
    id: "append",
    category: "Lister og samlinger",
    syntax: "liste.append(verdi)",
    title: "append legger til bakerst",
    summary: "append legger én ny verdi bakerst i listen.",
    explanation: "Listen blir endret direkte. append returnerer ikke den nye listen; derfor skal du vanligvis ikke skrive liste = liste.append(verdi).",
    example: "navn = [\"Ada\", \"Bo\"]\nnavn.append(\"Celine\")\nprint(navn)",
    result: "['Ada', 'Bo', 'Celine']",
    keywords: ["legg til liste", "ny verdi", "bakerst", "utvid liste", "append"],
  },
  {
    id: "insert",
    category: "Lister og samlinger",
    syntax: "liste.insert(indeks, verdi)",
    title: "insert setter inn på en bestemt plass",
    summary: "insert legger inn en verdi på ønsket indeks og flytter resten mot høyre.",
    explanation: "liste.insert(0, verdi) legger verdien først. Det første argumentet er plassnummeret.",
    example: "navn = [\"Bo\", \"Celine\"]\nnavn.insert(0, \"Ada\")\nprint(navn)",
    result: "['Ada', 'Bo', 'Celine']",
    keywords: ["sett inn liste", "legg til først", "bestemt plass", "indeks"],
  },
  {
    id: "remove",
    category: "Lister og samlinger",
    syntax: "liste.remove(verdi)",
    title: "remove fjerner en bestemt verdi",
    summary: "remove finner og fjerner det første elementet som er lik verdien.",
    explanation: "Du oppgir selve verdien, ikke plassnummeret. Hvis verdien ikke finnes, stopper Python med en feil.",
    example: "navn = [\"Ada\", \"Bo\", \"Ada\"]\nnavn.remove(\"Ada\")\nprint(navn)",
    result: "['Bo', 'Ada']",
    keywords: ["fjern fra liste", "slett verdi", "remove", "ta bort"],
  },
  {
    id: "pop",
    category: "Lister og samlinger",
    syntax: "liste.pop(indeks)",
    title: "pop tar ut og returnerer en listeverdi",
    summary: "pop fjerner verdien på en plass og gir verdien tilbake.",
    explanation: "Uten indeks tas siste verdi ut. Du kan lagre den fjernede verdien i en variabel.",
    example: "ko = [\"Ada\", \"Bo\", \"Celine\"]\nneste = ko.pop(0)\nprint(neste, ko)",
    result: "Ada ['Bo', 'Celine']",
    keywords: ["ta ut liste", "fjern indeks", "siste verdi", "kø", "pop"],
  },
  {
    id: "len-list",
    category: "Lister og samlinger",
    syntax: "len(liste)",
    title: "len teller listeverdier",
    summary: "len gir antall elementer i en liste eller annen samling.",
    explanation: "Resultatet er et heltall og passer som nevner når gjennomsnitt skal regnes ut.",
    example: "poeng = [4, 7, 9]\nprint(len(poeng))",
    result: "3",
    keywords: ["antall i liste", "tell verdier", "lengde liste", "hvor mange", "length"],
  },
  {
    id: "sort",
    category: "Lister og samlinger",
    syntax: "liste.sort()",
    title: "sort sorterer selve listen",
    summary: "sort endrer rekkefølgen i listen fra minst til størst eller alfabetisk.",
    explanation: "Bruk reverse=True for motsatt rekkefølge. Hvis originallisten må bevares, bruk sorted(liste) i stedet.",
    example: "tall = [9, 2, 7]\ntall.sort()\nprint(tall)",
    result: "[2, 7, 9]",
    commonMistake: "sort endrer listen og gir ikke en ny liste tilbake.",
    keywords: ["sorter", "rekkefølge", "stigende", "alfabetisk", "minste først"],
  },
  {
    id: "sorted",
    category: "Lister og samlinger",
    syntax: "sorted(samling, reverse=False)",
    title: "sorted lager en sortert liste",
    summary: "sorted returnerer en ny sortert liste uten å endre originalen.",
    explanation: "Dette virker med mange typer samlinger. reverse=True gir synkende rekkefølge.",
    example: "tall = [9, 2, 7]\nnye = sorted(tall, reverse=True)\nprint(nye)\nprint(tall)",
    result: "[9, 7, 2]\n[9, 2, 7]",
    keywords: ["sorter kopi", "synkende", "stigende", "rekkefølge", "behold original"],
  },
  {
    id: "list-comprehension",
    category: "Lister og samlinger",
    syntax: "[uttrykk for verdi in samling]",
    title: "listeforståelse bygger en liste med en løkke",
    summary: "En kort skrivemåte som lager én ny verdi for hvert element i en samling.",
    explanation: "Dette er nyttig når mønsteret er enkelt. Nybegynnere kan alltid skrive en vanlig for-løkke med append først.",
    example: "kvadrater = [tall ** 2 for tall in range(1, 6)]\nprint(kvadrater)",
    result: "[1, 4, 9, 16, 25]",
    keywords: ["list comprehension", "lag liste med løkke", "kort løkke", "kvadrattall"],
  },
  {
    id: "tuple",
    category: "Lister og samlinger",
    syntax: "(verdi1, verdi2)",
    title: "( ) med komma lager en tuppel",
    summary: "En tuppel er en ordnet samling som vanligvis ikke skal endres.",
    explanation: "Koordinater passer ofte som tupler. Du kan hente verdier med indeks eller pakke dem ut til flere variabler.",
    example: "punkt = (3, 5)\nx, y = punkt\nprint(x, y)",
    result: "3 5",
    keywords: ["tuple", "tuppel", "koordinat", "fast samling", "pakke ut"],
  },
  {
    id: "dict-create",
    category: "Lister og samlinger",
    syntax: "ordbok = {nøkkel: verdi}",
    title: "{ } lager en ordbok",
    summary: "En ordbok kobler tydelige nøkler til verdier.",
    explanation: "I stedet for plassnummer bruker du et navn som nøkkel. Det gjør data om en person, måling eller vare lettere å forstå.",
    example: "elev = {\"navn\": \"Ada\", \"poeng\": 9}\nprint(elev[\"navn\"])",
    result: "Ada",
    keywords: ["dictionary", "dict", "ordbok", "nøkkel verdi", "oppslag", "datafelt"],
  },
  {
    id: "dict-get",
    category: "Lister og samlinger",
    syntax: "ordbok.get(nøkkel, standard)",
    title: "get henter trygt fra en ordbok",
    summary: "get henter verdien, eller en standardverdi hvis nøkkelen mangler.",
    explanation: "Vanlige hakeparenteser gir KeyError hvis nøkkelen ikke finnes. get lar programmet fortsette med en verdi du velger.",
    example: "elev = {\"navn\": \"Ada\"}\nprint(elev.get(\"poeng\", 0))",
    result: "0",
    keywords: ["hent fra ordbok", "manglende nøkkel", "standardverdi", "dictionary get"],
  },
  {
    id: "dict-items",
    category: "Lister og samlinger",
    syntax: "ordbok.items()",
    title: "items gir nøkler og verdier",
    summary: "items brukes i en løkke når både nøkkelen og verdien trengs.",
    explanation: "I hver runde får du et par som kan pakkes ut til to variabler.",
    example: "poeng = {\"Ada\": 9, \"Bo\": 7}\nfor navn, verdi in poeng.items():\n    print(navn, verdi)",
    result: "Ada 9\nBo 7",
    keywords: ["gå gjennom ordbok", "nøkkel og verdi", "dictionary loop", "items"],
  },
  {
    id: "set",
    category: "Lister og samlinger",
    syntax: "set(samling)",
    title: "set lager en mengde uten duplikater",
    summary: "En mengde beholder bare én av hver verdi og har ingen fast rekkefølge.",
    explanation: "Mengder er nyttige til å finne unike verdier og sammenligne hvilke elementer samlinger har felles.",
    example: "navn = [\"Ada\", \"Bo\", \"Ada\"]\nunike = set(navn)\nprint(len(unike))",
    result: "2",
    keywords: ["mengde", "set", "unik", "fjern duplikater", "ulike verdier"],
  },

  {
    id: "if",
    category: "Valg og løkker",
    syntax: "if vilkår:",
    title: "if kjører kode når et vilkår er sant",
    summary: "if lar programmet velge. Koden som hører til, må ha innrykk.",
    explanation: "Python undersøker uttrykket etter if. Hvis svaret er True, kjøres den innrykkede blokken. Kolon varsler at en blokk kommer.",
    example: "temperatur = -3\nif temperatur < 0:\n    print(\"Det er frost.\")",
    result: "Det er frost.",
    commonMistake: "Husk kolon etter vilkåret og innrykk på neste linje.",
    keywords: ["hvis", "vilkår", "valg", "betingelse", "dersom", "sant"],
  },
  {
    id: "elif",
    category: "Valg og løkker",
    syntax: "elif annet_vilkår:",
    title: "elif prøver et nytt vilkår",
    summary: "elif betyr «ellers hvis» og undersøkes bare når tidligere vilkår var usanne.",
    explanation: "Du kan ha flere elif-grener. Python velger den første sanne grenen og hopper over resten.",
    example: "poeng = 7\nif poeng >= 10:\n    print(\"Høy\")\nelif poeng >= 5:\n    print(\"Middels\")\nelse:\n    print(\"Lav\")",
    result: "Middels",
    keywords: ["ellers hvis", "flere valg", "annet vilkår", "else if", "gren"],
  },
  {
    id: "else",
    category: "Valg og løkker",
    syntax: "else:",
    title: "else tar alle andre tilfeller",
    summary: "else kjører når ingen av vilkårene over var sanne.",
    explanation: "else har ikke et eget vilkår. Den er sikkerhetsnettet som samler alle gjenværende muligheter.",
    example: "alder = 10\nif alder >= 12:\n    print(\"Ungdom\")\nelse:\n    print(\"Under 12\")",
    result: "Under 12",
    commonMistake: "else skal ha kolon, men ikke et vilkår etter seg.",
    keywords: ["ellers", "alle andre", "alternativ", "hvis ikke", "siste gren"],
  },
  {
    id: "for",
    category: "Valg og løkker",
    syntax: "for verdi in samling:",
    title: "for gjentar kode for hver verdi",
    summary: "En for-løkke gir løkkevariabelen én verdi om gangen og kjører den innrykkede koden.",
    explanation: "Løkken stopper når samlingen er tom. Bruk den med range, lister, tekstlinjer og andre samlinger.",
    example: "for navn in [\"Ada\", \"Bo\", \"Celine\"]:\n    print(\"Hei\", navn)",
    result: "Hei Ada\nHei Bo\nHei Celine",
    commonMistake: "Husk kolon og innrykk. Kode uten innrykk er ikke med i løkken.",
    keywords: ["løkke", "gjenta", "for hver", "repetisjon", "gå gjennom", "loop"],
  },
  {
    id: "range",
    category: "Valg og løkker",
    syntax: "range(start, stopp, steg)",
    title: "range lager en tallfølge",
    summary: "range gir heltall fra start fram mot stopp. Stoppverdien er ikke med.",
    explanation: "range(1, 6) gir 1, 2, 3, 4, 5. Et tredje tall bestemmer steglengden. range(10, 0, -1) teller ned.",
    example: "for tall in range(2, 11, 2):\n    print(tall)",
    result: "2\n4\n6\n8\n10",
    commonMistake: "range(1, 6) stopper før 6.",
    keywords: ["tallfølge", "start stopp steg", "telle", "løkke tall", "fra til", "sekvens"],
  },
  {
    id: "while",
    category: "Valg og løkker",
    syntax: "while vilkår:",
    title: "while gjentar så lenge et vilkår er sant",
    summary: "En while-løkke fortsetter til vilkåret blir False eller løkken stoppes.",
    explanation: "Noe inne i løkken må vanligvis endre verdien som vilkåret bruker. Ellers kan løkken fortsette for alltid.",
    example: "tall = 3\nwhile tall > 0:\n    print(tall)\n    tall -= 1\nprint(\"Start!\")",
    result: "3\n2\n1\nStart!",
    commonMistake: "Hvis tall aldri endres, blir while tall > 0 en uendelig løkke.",
    keywords: ["mens", "så lenge", "gjenta til", "uendelig løkke", "loop", "betinget løkke"],
  },
  {
    id: "break",
    category: "Valg og løkker",
    syntax: "break",
    title: "break stopper nærmeste løkke",
    summary: "break avslutter en for- eller while-løkke med én gang.",
    explanation: "Programmet fortsetter på første linje etter løkken. Bruk ofte break inne i en if-test.",
    example: "for tall in range(1, 100):\n    if tall == 4:\n        break\n    print(tall)",
    result: "1\n2\n3",
    keywords: ["stopp løkke", "avbryt", "slutt å gjenta", "bryt ut", "break"],
  },
  {
    id: "continue",
    category: "Valg og løkker",
    syntax: "continue",
    title: "continue hopper til neste runde",
    summary: "continue hopper over resten av den nåværende runden, men stopper ikke løkken.",
    explanation: "Bruk det når enkelte verdier skal ignoreres mens resten behandles.",
    example: "for tall in range(1, 6):\n    if tall == 3:\n        continue\n    print(tall)",
    result: "1\n2\n4\n5",
    keywords: ["hopp over", "neste runde", "fortsett løkke", "skip", "ignorer verdi"],
  },
  {
    id: "enumerate",
    category: "Valg og løkker",
    syntax: "enumerate(samling, start=0)",
    title: "enumerate gir både nummer og verdi",
    summary: "enumerate brukes i løkker når du trenger både plassnummeret og elementet.",
    explanation: "Med start=1 kan det synlige nummeret begynne på 1 selv om Python-indekser vanligvis begynner på 0.",
    example: "navn = [\"Ada\", \"Bo\"]\nfor nummer, navn in enumerate(navn, start=1):\n    print(nummer, navn)",
    result: "1 Ada\n2 Bo",
    keywords: ["nummerer", "indeks i løkke", "nummer og verdi", "tell runder"],
  },
  {
    id: "zip",
    category: "Valg og løkker",
    syntax: "zip(liste1, liste2)",
    title: "zip kobler sammen verdier plass for plass",
    summary: "zip gir første verdi fra hver liste, så andre fra hver, og så videre.",
    explanation: "Løkken stopper når den korteste samlingen er tom. Dette passer til parallelle x- og y-verdier eller navn og poeng.",
    example: "navn = [\"Ada\", \"Bo\"]\npoeng = [9, 7]\nfor navn, verdi in zip(navn, poeng):\n    print(navn, verdi)",
    result: "Ada 9\nBo 7",
    keywords: ["koble lister", "to lister samtidig", "par", "plass for plass", "zip"],
  },
  {
    id: "pass",
    category: "Valg og løkker",
    syntax: "pass",
    title: "pass er en tom plassholder",
    summary: "pass gjør ingenting, men gjør en foreløpig tom kodeblokk gyldig.",
    explanation: "Python krever minst én innrykket kommando etter if, for, while og def. pass kan brukes mens planen bygges ferdig.",
    example: "if True:\n    pass  # Koden skal skrives senere\nprint(\"Programmet fortsetter.\")",
    result: "Programmet fortsetter.",
    keywords: ["gjør ingenting", "tom blokk", "plassholder", "senere", "midlertidig"],
  },

  {
    id: "def",
    category: "Funksjoner",
    syntax: "def navn(parametere):",
    title: "def lager en funksjon",
    summary: "En funksjon er en navngitt oppskrift som kan brukes flere ganger.",
    explanation: "Parametrene er navnelapper for verdiene funksjonen skal få når den kalles. Koden i funksjonen må ha innrykk.",
    example: "def dobbel(tall):\n    return tall * 2\n\nprint(dobbel(6))",
    result: "12",
    commonMistake: "Å definere funksjonen kjører den ikke. Den må kalles, for eksempel dobbel(6).",
    keywords: ["lag funksjon", "oppskrift", "definer", "parameter", "egen kommando", "gjenbruk kode"],
  },
  {
    id: "return",
    category: "Funksjoner",
    syntax: "return verdi",
    title: "return sender et svar tilbake",
    summary: "return avslutter funksjonen og gir en verdi tilbake til stedet der funksjonen ble kalt.",
    explanation: "Verdien kan lagres, skrives ut eller brukes i et nytt regnestykke. return er ikke det samme som print: print viser, mens return leverer.",
    example: "def areal(lengde, bredde):\n    return lengde * bredde\n\nsvar = areal(8, 5)\nprint(svar)",
    result: "40",
    keywords: ["send svar", "funksjon svar", "gi tilbake", "returverdi", "print eller return"],
  },
  {
    id: "parameter-default",
    category: "Funksjoner",
    syntax: "def navn(parameter=standard):",
    title: "standardverdi gjør et argument valgfritt",
    summary: "En parameter kan få en verdi som brukes når funksjonskallet ikke oppgir noe annet.",
    explanation: "I hilsen(navn, tegn=\"!\") er tegn valgfritt. Parametere uten standardverdi må stå før dem med standardverdi.",
    example: "def hilsen(navn, tegn=\"!\"):\n    print(\"Hei\", navn + tegn)\n\nhilsen(\"Ada\")\nhilsen(\"Bo\", \".\")",
    result: "Hei Ada!\nHei Bo.",
    keywords: ["valgfri parameter", "standard argument", "default", "funksjon innstilling"],
  },
  {
    id: "lambda",
    category: "Funksjoner",
    syntax: "lambda x: uttrykk",
    title: "lambda lager en liten funksjon på én linje",
    summary: "lambda er en kort funksjon uten vanlig navn og brukes ofte som sorteringsregel.",
    explanation: "For nybegynnere er def vanligvis tydeligere. Lambda er nyttig når en annen kommando trenger en enkel funksjon akkurat der.",
    example: "punkter = [(2, 9), (1, 4), (3, 2)]\npunkter.sort(key=lambda punkt: punkt[1])\nprint(punkter)",
    result: "[(3, 2), (1, 4), (2, 9)]",
    keywords: ["anonym funksjon", "kort funksjon", "sorteringsnøkkel", "avansert"],
  },
  {
    id: "import",
    category: "Funksjoner",
    syntax: "import bibliotek",
    title: "import henter et bibliotek",
    summary: "import gjør ferdige verktøy tilgjengelige i programmet.",
    explanation: "Etter import math bruker du biblioteknavnet foran kommandoen, for eksempel math.sqrt(25). Importer vanligvis øverst i programmet.",
    example: "import math\nprint(math.sqrt(25))",
    result: "5.0",
    commonMistake: "Stav biblioteknavnet nøyaktig. Enkelte eksterne biblioteker er ikke tilgjengelige i alle Python-miljøer.",
    keywords: ["bibliotek", "pakke", "modul", "hent verktøy", "installer", "library"],
  },
  {
    id: "import-as",
    category: "Funksjoner",
    syntax: "import bibliotek as kortnavn",
    title: "as gir biblioteket et kortnavn",
    summary: "Et vanlig kortnavn gjør lange biblioteknavn raskere å skrive.",
    explanation: "NumPy importeres ofte som np, pandas som pd og matplotlib.pyplot som plt. Følg disse vanlige navnene så eksempler blir lettere å forstå.",
    example: "import numpy as np\ntall = np.array([1, 2, 3])\nprint(tall * 2)",
    result: "[2 4 6]",
    keywords: ["kortnavn", "alias", "numpy np", "pandas pd", "matplotlib plt", "importer som"],
  },
  {
    id: "from-import",
    category: "Funksjoner",
    syntax: "from bibliotek import navn",
    title: "from import henter bestemte navn",
    summary: "Denne skrivemåten lar deg bruke utvalgte kommandoer uten biblioteknavnet foran.",
    explanation: "from math import sqrt gjør at du kan skrive sqrt(25). Å hente * betyr «alle navn», men kan gjøre det uklart hvor kommandoene kommer fra.",
    example: "from math import pi\nradius = 3\nprint(round(pi * radius ** 2, 2))",
    result: "28.27",
    keywords: ["hent fra bibliotek", "spesifikk kommando", "from", "import navn", "turtle import"],
  },

  {
    id: "sum",
    category: "Tall og statistikk",
    syntax: "sum(tall)",
    title: "sum legger sammen en samling",
    summary: "sum gir summen av alle tallene i en liste eller annen tallfølge.",
    explanation: "Start med en liste av tall. Hvis verdiene er lest fra fil som tekst, må de først gjøres om til int eller float.",
    example: "poeng = [4, 7, 9]\nprint(sum(poeng))",
    result: "20",
    keywords: ["summer liste", "legg sammen alle", "totalt", "sum av tall"],
  },
  {
    id: "min-max",
    category: "Tall og statistikk",
    syntax: "min(tall) / max(tall)",
    title: "min og max finner ytterverdiene",
    summary: "min finner minste verdi, og max finner største.",
    explanation: "De virker også alfabetisk på tekst. Samlingen må inneholde minst én verdi.",
    example: "temperaturer = [8, 13, 11, 16]\nprint(min(temperaturer), max(temperaturer))",
    result: "8 16",
    keywords: ["minste", "største", "lavest", "høyest", "minimum", "maksimum"],
  },
  {
    id: "statistics-mean",
    category: "Tall og statistikk",
    syntax: "statistics.mean(tall)",
    title: "mean finner gjennomsnittet",
    summary: "statistics.mean beregner det aritmetiske gjennomsnittet.",
    explanation: "Importer statistics først. Den samme beregningen kan skrives sum(tall) / len(tall), men mean uttrykker hensikten tydelig.",
    example: "import statistics\npoeng = [4, 7, 9]\nprint(statistics.mean(poeng))",
    result: "6.666666666666667",
    keywords: ["gjennomsnitt", "middelverdi", "mean", "statistikk", "snitt"],
  },
  {
    id: "statistics-median",
    category: "Tall og statistikk",
    syntax: "statistics.median(tall)",
    title: "median finner den midterste verdien",
    summary: "median sorterer tankemessig verdiene og finner midtverdien.",
    explanation: "Med et partall antall verdier blir medianen gjennomsnittet av de to i midten.",
    example: "import statistics\ntall = [2, 5, 100, 7, 8]\nprint(statistics.median(tall))",
    result: "7",
    keywords: ["median", "midtverdi", "statistikk", "midterste", "sentralmål"],
  },
  {
    id: "statistics-mode",
    category: "Tall og statistikk",
    syntax: "statistics.mode(verdier)",
    title: "mode finner typetallet",
    summary: "mode finner verdien som forekommer oftest.",
    explanation: "Typetall kan brukes på både tall og kategorier. Hvis flere verdier er like vanlige, bør du også kjenne til statistics.multimode.",
    example: "import statistics\nsvar = [2, 3, 3, 4, 3, 5]\nprint(statistics.mode(svar))",
    result: "3",
    keywords: ["typetall", "mest vanlig", "hyppigst", "modus", "statistikk"],
  },
  {
    id: "random-randint",
    category: "Tall og statistikk",
    syntax: "random.randint(min, maks)",
    title: "randint trekker et tilfeldig heltall",
    summary: "randint gir et heltall mellom begge grensene, inkludert min og maks.",
    explanation: "Importer random først. Hvert kall er et nytt tilfeldig forsøk, så resultatet kan endre seg fra kjøring til kjøring.",
    example: "import random\nkast = random.randint(1, 6)\nprint(kast)",
    keywords: ["tilfeldig tall", "random", "terning", "trekke tall", "heltall", "simulering"],
  },
  {
    id: "random-choice",
    category: "Tall og statistikk",
    syntax: "random.choice(liste)",
    title: "choice trekker én tilfeldig listeverdi",
    summary: "choice velger ett element fra en samling.",
    explanation: "Listen må ha minst én verdi. Det er nyttig til tilfeldig navn, spørsmål, farge eller handling.",
    example: "import random\nfarger = [\"rød\", \"grønn\", \"blå\"]\nprint(random.choice(farger))",
    keywords: ["tilfeldig valg", "trekk fra liste", "random choice", "velg en", "lotteri"],
  },
  {
    id: "math-sqrt",
    category: "Tall og statistikk",
    syntax: "math.sqrt(tall)",
    title: "sqrt finner kvadratroten",
    summary: "math.sqrt gir det ikke-negative tallet som ganget med seg selv gir utgangspunktet.",
    explanation: "Importer math først. Kvadratroten av 25 er 5 fordi 5 · 5 = 25.",
    example: "import math\nprint(math.sqrt(25))",
    result: "5.0",
    keywords: ["kvadratrot", "rot", "sqrt", "pythagoras", "math"],
  },
  {
    id: "math-pi",
    category: "Tall og statistikk",
    syntax: "math.pi",
    title: "pi gir en presis verdi av π",
    summary: "math.pi er konstanten π med mange desimaler.",
    explanation: "Importer math og bruk math.pi i formler for sirkelens omkrets og areal.",
    example: "import math\nradius = 4\nareal = math.pi * radius ** 2\nprint(round(areal, 2))",
    result: "50.27",
    keywords: ["pi", "sirkel", "omkrets", "areal", "konstant", "3.14"],
  },
  {
    id: "numpy-array",
    category: "Tall og statistikk",
    syntax: "np.array(liste)",
    title: "NumPy-array regner med mange tall samtidig",
    summary: "Et array ligner en liste, men matematiske operasjoner virker element for element.",
    explanation: "Importer numpy as np. Hvis x er et array, lager x ** 2 kvadratet av hver verdi. Dette er svært nyttig til funksjonsgrafer.",
    example: "import numpy as np\nx = np.array([1, 2, 3])\nprint(x ** 2)",
    result: "[1 4 9]",
    keywords: ["numpy", "array", "mange tall", "vektor", "elementvis", "tabell tall"],
  },
  {
    id: "numpy-linspace",
    category: "Tall og statistikk",
    syntax: "np.linspace(start, stopp, antall)",
    title: "linspace lager jevnt fordelte x-verdier",
    summary: "linspace lager ønsket antall tall fra start til stopp, og begge endepunktene er med.",
    explanation: "Til en jevn funksjonsgraf brukes ofte 200–500 x-verdier. Dette gir en glattere kurve enn en kort liste.",
    example: "import numpy as np\nx = np.linspace(-2, 2, 5)\nprint(x)",
    result: "[-2. -1.  0.  1.  2.]",
    keywords: ["jevne tall", "x verdier", "graf", "numpy", "tallintervall", "linspace"],
  },

  {
    id: "open-read",
    category: "Filer og data",
    syntax: "with open(\"fil.txt\", encoding=\"utf-8\") as fil:",
    title: "open åpner en tekstfil",
    summary: "with open gjør en lokal tekstfil tilgjengelig i den innrykkede blokken og lukker den etterpå.",
    explanation: "Filnavnet må stemme nøyaktig med filen som er lagt til. encoding=\"utf-8\" gjør norske tegn trygge.",
    example: "with open(\"navn.txt\", encoding=\"utf-8\") as fil:\n    for linje in fil:\n        print(linje.strip())",
    commonMistake: "En fil må legges til ved editoren før nettleser-Python kan åpne den.",
    keywords: ["les fil", "åpne txt", "tekstfil", "lokal fil", "read", "filnavn", "with"],
  },
  {
    id: "file-read",
    category: "Filer og data",
    syntax: "fil.read()",
    title: "read leser hele filen som én tekst",
    summary: "read henter alt innholdet fra filen på én gang.",
    explanation: "Dette passer til mindre tekstfiler. Hvis du vil behandle én linje om gangen, kan du bruke en for-løkke direkte over filen.",
    example: "with open(\"tekst.txt\", encoding=\"utf-8\") as fil:\n    innhold = fil.read()\nprint(innhold)",
    keywords: ["les hele fil", "filinnhold", "tekst fra fil", "read all"],
  },
  {
    id: "file-write",
    category: "Filer og data",
    syntax: "open(\"fil.txt\", \"w\")",
    title: "w åpner en fil for skriving",
    summary: "Skrivemodus w lager en ny fil eller erstatter innholdet i en eksisterende fil.",
    explanation: "Bruk fil.write(tekst) i with-blokken. I Skolepython er filen midlertidig og forsvinner når kjøringen avsluttes. Les og skriv ut innholdet i samme kjøring; bruk «Last ned .py» for å lagre selve programmet.",
    example: "with open(\"svar.txt\", \"w\", encoding=\"utf-8\") as fil:\n    fil.write(\"Resultat: 42\\n\")",
    commonMistake: "w overskriver gammelt innhold. Bruk a hvis du vil legge til bakerst.",
    keywords: ["skriv fil", "lag tekstfil", "lagre tekst", "write", "overskriv", "fil ut"],
  },
  {
    id: "csv-reader",
    category: "Filer og data",
    syntax: "csv.DictReader(fil, delimiter=\";\")",
    title: "DictReader leser en CSV-tabell med kolonnenavn",
    summary: "Hver rad blir en ordbok der overskriftene er nøkler.",
    explanation: "Importer csv. Norske CSV-filer bruker ofte semikolon fordi komma brukes som desimalskilletegn. Se på første linje for å finne riktig delimiter.",
    example: "import csv\n\nwith open(\"data.csv\", encoding=\"utf-8-sig\", newline=\"\") as fil:\n    leser = csv.DictReader(fil, delimiter=\";\")\n    for rad in leser:\n        print(rad[\"navn\"], rad[\"poeng\"])",
    commonMistake: "Kolonnenavnet må være helt likt overskriften i filen.",
    keywords: ["csv", "tabell", "kolonne", "rad", "regneark", "dictreader", "semikolon", "delimiter"],
  },
  {
    id: "pandas-read-csv",
    category: "Filer og data",
    syntax: "pd.read_csv(\"data.csv\", sep=\";\")",
    title: "pandas leser en hel CSV-tabell",
    summary: "read_csv lager en DataFrame som kan filtreres, regnes på og tegnes.",
    explanation: "Importer pandas as pd. sep må passe med skilletegnet. decimal=\",\" kan brukes når desimaltallene i filen har komma.",
    example: "import pandas as pd\n\ntabell = pd.read_csv(\"data.csv\", sep=\";\", decimal=\",\")\nprint(tabell.head())",
    keywords: ["pandas", "les csv", "dataframe", "regneark", "tabell", "kolonner", "analyse"],
  },
  {
    id: "pandas-column",
    category: "Filer og data",
    syntax: "tabell[\"kolonne\"]",
    title: "hakeparentes henter en DataFrame-kolonne",
    summary: "Kolonnenavnet mellom anførselstegn velger én navngitt kolonne.",
    explanation: "Du kan bruke .mean(), .min(), .max() og andre operasjoner på den valgte kolonnen.",
    example: "import pandas as pd\n\ntabell = pd.DataFrame({\"poeng\": [4, 7, 9]})\nprint(tabell[\"poeng\"].mean())",
    result: "6.666666666666667",
    keywords: ["pandas kolonne", "hent kolonne", "dataframe", "gjennomsnitt kolonne", "tabellfelt"],
  },

  {
    id: "plt-plot",
    category: "Tegning",
    syntax: "plt.plot(x, y)",
    title: "plot tegner en linjegraf",
    summary: "Matplotlib kobler sammen punktene som lages av x- og y-verdiene.",
    explanation: "Importer matplotlib.pyplot as plt. x og y må ha like mange verdier. Legg til aksetitler, rutenett og plt.show() før grafen leveres.",
    example: "import matplotlib.pyplot as plt\n\nx = [0, 1, 2, 3]\ny = [0, 1, 4, 9]\nplt.plot(x, y, marker=\"o\")\nplt.xlabel(\"x\")\nplt.ylabel(\"f(x)\")\nplt.grid()\nplt.show()",
    keywords: ["tegn graf", "linjegraf", "funksjon", "matplotlib", "plot", "kurve"],
  },
  {
    id: "plt-labels",
    category: "Tegning",
    syntax: "plt.xlabel(...) / plt.ylabel(...) / plt.title(...) ",
    title: "xlabel, ylabel og title navngir grafen",
    summary: "Kommandoene gir x-aksen, y-aksen og hele grafen tydelige titler.",
    explanation: "På vurderinger bør aksetitlene også ha enheter når det er relevant, for eksempel Tid (timer) og Pris (kr).",
    example: "import matplotlib.pyplot as plt\n\nx = [0, 1, 2, 3]\ny = [0, 1, 4, 9]\nplt.plot(x, y)\nplt.xlabel(\"Tid (timer)\")\nplt.ylabel(\"Pris (kr)\")\nplt.title(\"Pris for leie\")\nplt.show()",
    keywords: ["aksetittel", "navn på akse", "x akse", "y akse", "graf tittel", "enhet", "eksamen"],
  },
  {
    id: "plt-limits",
    category: "Tegning",
    syntax: "plt.xlim(min, maks) / plt.ylim(min, maks)",
    title: "xlim og ylim bestemmer grafutsnittet",
    summary: "Grensene bestemmer hvilke x- og y-verdier koordinatsystemet viser.",
    explanation: "Velg et utsnitt som viser de viktige punktene uten store tomme områder. Utsnittet endrer ikke funksjonen, bare visningen.",
    example: "import matplotlib.pyplot as plt\n\nx = [0, 1, 2, 3]\ny = [0, 1, 4, 9]\nplt.plot(x, y)\nplt.xlim(-5, 5)\nplt.ylim(-10, 20)\nplt.show()",
    keywords: ["aksegrenser", "graf utsnitt", "målestokk", "zoom", "x min maks", "y min maks"],
  },
  {
    id: "plt-aspect",
    category: "Tegning",
    syntax: "ax.set_aspect(1, adjustable=\"box\")",
    title: "set_aspect bestemmer forholdet mellom aksene",
    summary: "Akseforhold 1 gjør én x-enhet og én y-enhet like lange på arket.",
    explanation: "Bruk \"auto\" når grafen skal fylle plassen. Bruk 1 når geometriske former og stigning skal vises med lik fysisk målestokk på aksene.",
    example: "import matplotlib.pyplot as plt\n\nx = [0, 1, 2, 3]\ny = [0, 1, 4, 9]\nplt.plot(x, y)\nfig, ax = plt.subplots()\nax.set_aspect(1, adjustable=\"box\")\nplt.show()",
    keywords: ["akseforhold", "forhold mellom aksene", "like enheter", "målestokk", "aspect", "eksamen"],
  },
  {
    id: "plt-scatter",
    category: "Tegning",
    syntax: "plt.scatter(x, y)",
    title: "scatter tegner et punktdiagram",
    summary: "scatter viser hvert koordinatpar som et eget punkt uten å koble dem sammen.",
    explanation: "Punktdiagram passer til måledata og til å undersøke sammenheng mellom to variabler.",
    example: "import matplotlib.pyplot as plt\n\nhoyde = [150, 160, 170, 180]\nrekkevidde = [145, 158, 172, 177]\nplt.scatter(hoyde, rekkevidde)\nplt.xlabel(\"Høyde (cm)\")\nplt.ylabel(\"Rekkevidde (cm)\")\nplt.show()",
    keywords: ["punktdiagram", "spredningsdiagram", "scatter", "måledata", "korrelasjon", "punkter"],
  },
  {
    id: "plt-bar",
    category: "Tegning",
    syntax: "plt.bar(kategorier, verdier)",
    title: "bar tegner et stolpediagram",
    summary: "bar viser én stolpe for hver kategori og verdi.",
    explanation: "Stolpediagram passer til kategorier. Bruk tydelige navn og start vanligvis y-aksen ved 0 så forskjellene ikke overdrives.",
    example: "import matplotlib.pyplot as plt\n\nfag = [\"Matte\", \"Norsk\", \"Engelsk\"]\npoeng = [8, 6, 9]\nplt.bar(fag, poeng)\nplt.ylabel(\"Poeng\")\nplt.show()",
    keywords: ["stolpediagram", "søylediagram", "bar chart", "kategorier", "statistikk"],
  },
  {
    id: "plt-savefig",
    category: "Tegning",
    syntax: "plt.savefig(\"graf.png\", dpi=300)",
    title: "savefig lagrer grafen som bilde",
    summary: "savefig lager en PNG-, SVG- eller PDF-fil av figuren.",
    explanation: "Filtypen bestemmes av slutten på filnavnet. Kall gjerne savefig før show. Filen ligger midlertidig i Python. For å laste ned grafen på enheten bruker du «Lagre bilde» ved resultatet.",
    example: "import matplotlib.pyplot as plt\n\nx = [0, 1, 2, 3]\ny = [0, 1, 4, 9]\nplt.plot(x, y)\nplt.tight_layout()\nplt.savefig(\"graf.png\", dpi=300)\nplt.show()",
    keywords: ["lagre graf", "last ned bilde", "png", "svg", "eksporter", "save figure"],
  },
  {
    id: "turtle-forward",
    category: "Tegning",
    syntax: "forward(lengde) / backward(lengde)",
    title: "forward og backward flytter Turtle",
    summary: "Turtle går framover eller bakover i retningen den peker og tegner hvis pennen er nede.",
    explanation: "Importer med from turtle import *. Lengden måles i tegneenheter og kan lagres i en variabel.",
    example: "from turtle import *\nforward(100)\nbackward(40)\ndone()",
    keywords: ["turtle fram", "turtle bak", "tegn strek", "flytt penn", "forward", "backward"],
  },
  {
    id: "turtle-turn",
    category: "Tegning",
    syntax: "left(vinkel) / right(vinkel)",
    title: "left og right snur Turtle i grader",
    summary: "Kommandoene endrer retningen uten å flytte pennen.",
    explanation: "En hel omdreining er 360°. Et kvadrat bruker 90° etter hver side. En regulær n-kant bruker ofte 360 / n som ytre dreievinkel.",
    example: "from turtle import *\nfor side in range(4):\n    forward(100)\n    left(90)\ndone()",
    keywords: ["turtle sving", "venstre", "høyre", "vinkel", "grader", "roter", "mangekant"],
  },
  {
    id: "turtle-pen",
    category: "Tegning",
    syntax: "penup() / pendown()",
    title: "penup og pendown løfter og senker pennen",
    summary: "Med pennen oppe kan Turtle flyttes uten å tegne.",
    explanation: "Bruk penup, gå til ny plass med goto, og bruk pendown før neste strek skal tegnes.",
    example: "from turtle import *\nforward(50)\npenup()\nforward(50)\npendown()\nforward(50)\ndone()",
    keywords: ["løft penn", "senk penn", "flytt uten strek", "turtle mellomrom", "pen up"],
  },
  {
    id: "turtle-style",
    category: "Tegning",
    syntax: "color(farge) / pensize(tykkelse)",
    title: "color og pensize endrer Turtle-streken",
    summary: "Velg strekfarge og tykkelse før neste linje tegnes.",
    explanation: "Farger kan skrives som engelske navn eller hex-koder som #f06f51. Skaperverkstedet kan også bearbeide tykkelse og farge ved SVG-eksport.",
    example: "from turtle import *\ncolor(\"#f06f51\")\npensize(5)\nforward(120)\ndone()",
    keywords: ["turtle farge", "strektykkelse", "pensize", "color", "hex", "penn"],
  },
  {
    id: "turtle-circle",
    category: "Tegning",
    syntax: "circle(radius, extent=360)",
    title: "circle tegner en sirkel eller sirkelbue",
    summary: "circle tegner med valgt radius; extent kan begrense vinkelen på buen.",
    explanation: "circle(80) tegner en hel sirkel. circle(80, 180) tegner en halvsirkel. Fortegnet på radius bestemmer hvilken side sentrum ligger på.",
    example: "from turtle import *\nfor radius in [30, 60, 90]:\n    circle(radius)\ndone()",
    keywords: ["turtle sirkel", "sirkelbue", "radius", "circle", "geometri"],
  },

  {
    id: "try-except",
    category: "Feil og kontroll",
    syntax: "try: ... except Feiltype:",
    title: "try og except håndterer forventede feil",
    summary: "Python prøver koden og går til except hvis den angitte feilen oppstår.",
    explanation: "Dette brukes når en feil er en mulig del av programmet, for eksempel ugyldig brukerinput. Fang helst en bestemt feiltype, ikke alle feil uten forklaring.",
    example: "tekst = \"tolv\"\ntry:\n    tall = int(tekst)\n    print(tall)\nexcept ValueError:\n    print(\"Skriv et heltall med sifre.\")",
    result: "Skriv et heltall med sifre.",
    keywords: ["fang feil", "håndter feil", "exception", "valueerror", "prøv kode", "unngå krasj"],
  },
  {
    id: "assert",
    category: "Feil og kontroll",
    syntax: "assert vilkår, \"melding\"",
    title: "assert kontrollerer at noe må være sant",
    summary: "assert stopper med en tydelig melding hvis forutsetningen er False.",
    explanation: "Dette er nyttig til å teste egne funksjoner og oppdage feil tidlig. Det er først og fremst et utviklingsverktøy, ikke vanlig brukerhåndtering.",
    example: "def dobbel(tall):\n    return tall * 2\n\nassert dobbel(4) == 8, \"dobbel ga feil svar\"\nprint(\"Testen bestod.\")",
    result: "Testen bestod.",
    keywords: ["test kode", "kontroller svar", "må være sant", "påstand", "feilsøking"],
  },
  {
    id: "is-none",
    category: "Feil og kontroll",
    syntax: "verdi is None",
    title: "is None undersøker om en verdi mangler",
    summary: "None er Pythons verdi for «ingen verdi her».",
    explanation: "Bruk is None og is not None, ikke == None som fast skrivemåte. None er forskjellig fra 0, tom tekst og False.",
    example: "svar = None\nif svar is None:\n    print(\"Ingen verdi ennå.\")",
    result: "Ingen verdi ennå.",
    keywords: ["ingen verdi", "none", "tom", "mangler", "null", "is"],
  },
  {
    id: "help",
    category: "Feil og kontroll",
    syntax: "help(navn)",
    title: "help viser Pythons innebygde dokumentasjon",
    summary: "help forklarer en funksjon, klasse eller modul direkte i resultatfeltet.",
    explanation: "Den tekniske teksten kan være krevende, men signaturen øverst viser ofte hvilke argumenter kommandoen tar.",
    example: "help(round)",
    keywords: ["hjelp kommando", "dokumentasjon", "hvordan virker", "argumenter", "python manual"],
  },
  {
    id: "dir",
    category: "Feil og kontroll",
    syntax: "dir(verdi)",
    title: "dir viser tilgjengelige navn og metoder",
    summary: "dir lager en liste over ting et objekt eller bibliotek kan gjøre.",
    explanation: "Listen kan være lang og teknisk. Bruk den til utforsking når du kjenner objektet, men ikke vet navnet på metoden.",
    example: "tekst = \"Ada\"\nprint([navn for navn in dir(tekst) if not navn.startswith(\"_\")])",
    keywords: ["hvilke metoder", "kommandoer på objekt", "utforsk bibliotek", "tilgjengelige navn", "inspect"],
  },
  ...mathLibraryCommands,
];
