import { readStored, writeStored } from "../lib/storage";
import { useState } from "react";
import type { Module } from "../content/course";
import { lessonMeta, lessonSteps } from "../content/learning";
export default function LessonPanel({module:m, step, onStep, onTry, onCheck, onComplete, completed, feedback, onHelp, onPygame}:{module:Module;step:number;onStep:(step:number)=>void;onTry:(code:string)=>void;onCheck:()=>void;onComplete:()=>void;completed:boolean;feedback:string;onHelp:(query:string)=>void;onPygame:()=>void}) {
  const meta=lessonMeta[m.id];
  const [prediction,setPrediction]=useState(()=>readStored<string>(`skolepython-prediction-${m.id}`, "", v=>typeof v==="string"));
  const [noteSaved,setNoteSaved]=useState(true);
  const [hint,setHint]=useState(false),[trial,setTrial]=useState(0);
  return <aside className="lesson-panel" aria-label="Læringssteg">
    <div className="lesson-title"><small>MODUL {m.id} · {meta.minutes}</small><h1>{m.title}</h1><p>{meta.goal}</p><details><summary>Før du begynner</summary><p>{meta.before}</p></details></div>
    <nav className="lesson-step-nav" aria-label="Arbeidsflyt">{lessonSteps.map((label,i)=><button key={label} aria-current={step===i?"step":undefined} onClick={()=>onStep(i)}><span>{i+1}</span>{label}</button>)}</nav>
    <div className="lesson-body" key={step}>
      {step===0 && <><h2>{m.question}</h2><p>{m.intro}</p><h3>{m.refresh.title}</h3><p>{m.refresh.body}</p>{m.refresh.examples.map(e=><div className="small-example" key={e.code}><code>{e.code}</code><p>{e.explanation}</p></div>)}{m.theory.map(t=><details key={t.title}><summary>{t.title}</summary><p>{t.body}</p>{t.code&&<pre><code>{t.code}</code></pre>}<ol>{t.steps.map(s=><li key={s}>{s}</li>)}</ol><p>{t.why}</p></details>)}</>}
      {step===1 && <><h2>Les før du kjører</h2><p>Hvilke verdier får variablene? Hva blir skrevet ut eller tegnet?</p><pre><code>{m.starterCode}</code></pre><label>Min forutsigelse<textarea value={prediction} onChange={e=>{setPrediction(e.target.value);setNoteSaved(writeStored(`skolepython-prediction-${m.id}`,e.target.value));}} placeholder="Jeg tror resultatet blir … fordi …" /></label><p className="muted">{noteSaved?"Forutsigelsen lagres på denne enheten.":"Kunne ikke lagre notatet. Kopier det før du lukker siden."}</p><button onClick={()=>onTry(m.starterCode)}>Prøv eksemplet i koden</button>{m.id===1&&<table><thead><tr><th>Etter linje</th><th>Det Python husker</th></tr></thead><tbody><tr><td>1</td><td>pris = 800</td></tr><tr><td>2</td><td>rabatt = 0.25</td></tr><tr><td>3</td><td>ny_pris = 600.0</td></tr></tbody></table>}</>}
      {step===2 && <><h2>Ett lite steg om gangen</h2><label>Velg et delsteg<select value={Math.min(trial,m.progression.steps.length-1)} onChange={e=>setTrial(Number(e.target.value))}>{m.progression.steps.map((t,i)=><option key={t.title} value={i}>{i+1}. {t.title}{m.id===1&&i>1?" · Valgfritt":""}{m.id===10?i<2?" · Lister":i===2?" · TXT":" · CSV":""}</option>)}</select></label>{(()=>{const t=m.progression.steps[Math.min(trial,m.progression.steps.length-1)];return <><h3>{t.title}</h3><p>{t.body}</p><pre><code>{t.code}</code></pre><button className="primary" onClick={()=>onTry(t.code)}>Prøv koden</button><p>{t.tryThis}</p>{t.upgrade&&<details><summary>{t.upgrade.title}</summary><p>{t.upgrade.body}</p><pre><code>{t.upgrade.code}</code></pre></details>}</>})()}<details><summary>Skrivehjelp linje for linje</summary><ol>{m.typingSteps.map((t,i)=><li key={i}>{t.code&&<pre><code>{t.code}</code></pre>}<p>{t.explanation}</p>{t.why&&<p>{t.why}</p>}</li>)}</ol></details>{m.id===3&&<button onClick={()=>onHelp("while")}>Hvordan virker while?</button>}</>}
      {step===3 && <><h2>Forklar det du ser</h2><ol>{m.observe.map(q=><li key={q}>{q}</li>)}</ol><div className="notice">«Programmet skal … Først … Deretter … Resultatet blir … fordi …»</div><p>Bruk «Følg stegvis» under flere verktøy. Forutsi en variabel før du går til neste linje.</p></>}
      {step===4 && <><h2>Endre programmet</h2><p>{m.task}</p><button onClick={()=>setHint(!hint)} aria-expanded={hint}>{hint?"Skjul hint":"Gi meg et hint"}</button>{hint&&<p className="notice">{m.taskHint}</p>}<h3>Kontroller løsningen</h3><ul>{meta.tests.map(t=><li key={t}>{t}</li>)}</ul><button className="primary" onClick={onCheck}>Sjekk resultatet</button>{feedback&&<p className="notice" role="status">{feedback}</p>}<h3>Lag noe selv · valgfritt</h3><p>{meta.extra}</p>{m.id===8&&<button onClick={onPygame}>Åpne Pygame-kurset →</button>}<details><summary>{m.polish.title}</summary><p>{m.polish.body}</p><pre><code>{m.polish.after}</code></pre><p>{m.polish.explanation}</p></details><p className="muted">Fullført er din egen vurdering etter at du har testet og forklart løsningen.</p><button onClick={onComplete}>{completed?"✓ Markert som fullført":"Jeg har testet og forklart"}</button></>}
    </div>
    <footer><button disabled={step===0} onClick={()=>onStep(step-1)}>← Forrige</button><span>{step+1} av 5</span><button disabled={step===4} onClick={()=>onStep(step+1)}>Neste →</button></footer>
  </aside>;
}
