

export type CurriculumFit = "Direkte" | "God støtte" | "Supplerende";

export type CurriculumGrade = "Alle" | "8" | "9" | "10";


export type CurriculumGoal = {
  id: string;
  grade: "8" | "9" | "10";
  goal: string;
  fit: CurriculumFit;
  activity: string;
  tools: string[];
  moduleIds: number[];
};


export const curriculumSources = {
  "8": "https://www.udir.no/lk20/mat01-06/kompetansemaal-og-vurdering/kv1027?lang=nob",
  "9": "https://www.udir.no/lk20/mat01-06/kompetansemaal-og-vurdering/kv1028?lang=nob",
  "10": "https://www.udir.no/lk20/mat01-06/kompetansemaal-og-vurdering/kv1029?lang=nob",
} as const;


export const curriculumGoals: CurriculumGoal[] = [
  {
    id: "8-potenser",
    grade: "8",
    goal: "regne med potenser og kvadratrøtter og forklare framgangsmåter og resultater",
    fit: "God støtte",
    activity: "Sammenlign gjentatt multiplikasjon med **, lag en tabell med kvadrattall og kontroller kvadratrøtter med math.sqrt.",
    tools: ["**", "math.sqrt", "løkker", "tabeller"],
    moduleIds: [1, 3],
  },
  {
    id: "8-regneegenskaper",
    grade: "8",
    goal: "bruke kommutative, assosiative og distributive egenskaper til å utvikle og kommunisere strategier for hoderegning og skriftlig regning",
    fit: "Supplerende",
    activity: "La Python kontrollere flere omskrivinger, og forklar hvorfor uttrykkene gir samme svar for ulike verdier.",
    tools: ["variabler", "uttrykk", "print", "SymPy"],
    moduleIds: [1],
  },
  {
    id: "8-faktorisering",
    grade: "8",
    goal: "beskrive og utforske faktorisering og primtallsfaktorisering og bruke det i brøkregning",
    fit: "God støtte",
    activity: "Test divisorer med %, bygg en primtallsalgoritme og bruk SymPy til å kontrollere faktoriseringen.",
    tools: ["%", "if", "løkker", "SymPy"],
    moduleIds: [2, 3],
  },
  {
    id: "8-monstre",
    grade: "8",
    goal: "utforske og generalisere geometriske mønstre og tallmønstre med egne ord og algebraisk",
    fit: "Direkte",
    activity: "Lag tallfølger med løkker og geometriske mønstre med Turtle. Endre regelen og beskriv hva som alltid skjer.",
    tools: ["range", "løkker", "Turtle", "variabler"],
    moduleIds: [3, 7],
  },
  {
    id: "8-uttrykk",
    grade: "8",
    goal: "lage og forklare regneuttrykk med tall, variabler og konstanter knyttet til praktiske situasjoner",
    fit: "Direkte",
    activity: "Oversett pris, rabatt, lengde eller fart til navngitte variabler og forklar uttrykket linje for linje.",
    tools: ["variabler", "regneoperatorer", "f-tekst"],
    moduleIds: [1],
  },
  {
    id: "8-ligninger",
    grade: "8",
    goal: "lage og løse ligninger knyttet til praktiske situasjoner og kritisk vurdere løsninger",
    fit: "God støtte",
    activity: "Søk etter løsninger med en løkke, eller bruk SymPy. Sett svaret tilbake i situasjonen og vurder om det er rimelig.",
    tools: ["løkker", "if", "SymPy", "kontrollregning"],
    moduleIds: [1, 2, 3],
  },
  {
    id: "8-ulikheter",
    grade: "8",
    goal: "bruke ulike strategier for å løse ulikheter og vurdere om løsninger er gyldige",
    fit: "God støtte",
    activity: "Bruk sammenligninger og if til å teste hvilke verdier som oppfyller en ulikhet, og vis løsningene i en tabell.",
    tools: ["< og >", "if/else", "range", "tabeller"],
    moduleIds: [2, 3],
  },
  {
    id: "8-funksjoner",
    grade: "8",
    goal: "beskrive, sammenligne og utforske funksjoner knyttet til praktiske situasjoner",
    fit: "Direkte",
    activity: "Skriv funksjoner for to praktiske modeller, endre parameterne og sammenlign tabeller og grafer.",
    tools: ["def", "return", "Matplotlib", "tabeller"],
    moduleIds: [4, 6, 9],
  },
  {
    id: "8-representasjoner",
    grade: "8",
    goal: "bruke situasjoner, tabeller, grafer og uttrykk til å representere funksjoner og vise sammenhenger mellom representasjonene",
    fit: "Direkte",
    activity: "La samme funksjon vises som tekstsituasjon, uttrykk, verditabell og graf. Pek ut hvor samme informasjon finnes i alle fire.",
    tools: ["funksjoner", "Pandas", "Matplotlib", "lister", "uttrykk"],
    moduleIds: [4, 6, 9, 10],
  },
  {
    id: "8-algoritmer",
    grade: "8",
    goal: "utforske hvordan algoritmer kan skapes, testes og forbedres ved hjelp av programmering",
    fit: "Direkte",
    activity: "Lag en første løsning, test den med ulike verdier, finn en svakhet og forbedre algoritmen i små steg.",
    tools: ["if/else", "løkker", "funksjoner", "Turtle"],
    moduleIds: [2, 3, 4, 7, 8],
  },
  {
    id: "9-maleenheter",
    grade: "9",
    goal: "lage og løse problemer som handler om sammensatte måleenheter",
    fit: "God støtte",
    activity: "Lag omregningsfunksjoner for km/t og m/s, pris per kilogram eller energiforbruk per time.",
    tools: ["variabler", "funksjoner", "enhetstekst"],
    moduleIds: [1, 4],
  },
  {
    id: "9-figurer",
    grade: "9",
    goal: "utforske egenskapene ved ulike todimensjonale figurer og forklare begrepene formlikhet og kongruens",
    fit: "Direkte",
    activity: "Tegn figurer med Turtle, kopier dem med samme eller endret målestokk og sammenlign sider og vinkler.",
    tools: ["Turtle", "løkker", "målestokk", "vinkler"],
    moduleIds: [7],
  },
  {
    id: "9-pytagoras",
    grade: "9",
    goal: "bruke formlikhet og Pytagoras’ læresetning til utforsking av praktiske situasjoner",
    fit: "Direkte",
    activity: "Beregn den ukjente siden, tegn trekanten i riktig målestokk og kontroller avstanden mellom koordinatene.",
    tools: ["Turtle", "math.sqrt", "koordinater", "funksjoner"],
    moduleIds: [4, 7],
  },
  {
    id: "9-trekanter",
    grade: "9",
    goal: "utforske, beskrive og argumentere for sammenhenger mellom sidelengdene i trekanter",
    fit: "Direkte",
    activity: "Test trekantulikheten for mange sidelengder, og tegn bare kombinasjonene som faktisk kan danne en trekant.",
    tools: ["if/else", "løkker", "Turtle"],
    moduleIds: [2, 3, 7],
  },
  {
    id: "9-forutsetninger",
    grade: "9",
    goal: "utforske og argumentere for hvordan det å endre forutsetninger i geometriske problemstillinger påvirker løsninger både praktisk og algebraisk",
    fit: "Direkte",
    activity: "Gjør sidelengde, antall sider og vinkel til variabler. Endre én verdi om gangen og forklar virkningen på figuren.",
    tools: ["Turtle", "variabler", "løkker", "SVG"],
    moduleIds: [1, 7],
  },
  {
    id: "9-overflate-volum",
    grade: "9",
    goal: "bruke og argumentere for formler for overflateareal og volum av tredimensjonale figurer",
    fit: "God støtte",
    activity: "Lag funksjoner for overflate og volum, sammenlign figurer i en tabell og undersøk hvordan dobling av mål påvirker resultatet.",
    tools: ["funksjoner", "potenser", "tabeller"],
    moduleIds: [1, 4],
  },
  {
    id: "9-statistikk-kritikk",
    grade: "9",
    goal: "tolke og kritisk vurdere statistiske framstillinger fra media og lokalsamfunnet",
    fit: "God støtte",
    activity: "Gjenskap en graf med Matplotlib, endre aksestart og skala og diskuter hvordan inntrykket forandres.",
    tools: ["Matplotlib", "Pandas", "CSV", "akser", "datasett"],
    moduleIds: [4, 9, 10],
  },
  {
    id: "9-sentral-spredning",
    grade: "9",
    goal: "regne på sentralmål og spredningsmål i egne og reelle datasett og bruke resultatene til å beskrive dataene",
    fit: "Direkte",
    activity: "Importer data fra .txt eller .csv og beregn gjennomsnitt, median, variasjonsbredde og standardavvik.",
    tools: ["NumPy", "Pandas", "lister", "CSV", "tabeller"],
    moduleIds: [4, 10],
  },
  {
    id: "9-framstillinger",
    grade: "9",
    goal: "sammenligne og argumentere for hvordan framstillinger av tall og data kan brukes for å fremme ulike synspunkter",
    fit: "Direkte",
    activity: "Lag to korrekte grafer av samme datasett med ulike utsnitt, diagramtyper eller skalaer og vurder budskapet.",
    tools: ["Matplotlib", "Pandas", "CSV", "grafer", "akser"],
    moduleIds: [4, 9, 10],
  },
  {
    id: "9-sannsynlighet",
    grade: "9",
    goal: "beregne og vurdere sannsynlighet i statistikk og spill",
    fit: "Direkte",
    activity: "Beregn teoretisk sannsynlighet, simuler spillet og vurder om regelen er rettferdig.",
    tools: ["random", "tellere", "andeler", "if"],
    moduleIds: [2, 5],
  },
  {
    id: "9-simulering",
    grade: "9",
    goal: "simulere utfall i tilfeldige forsøk og beregne sannsynligheten for at noe skal inntreffe, ved å bruke programmering",
    fit: "Direkte",
    activity: "Gjenta et tilfeldig forsøk mange ganger, tell ønskede utfall og sammenlign relativ frekvens med teoretisk sannsynlighet.",
    tools: ["random", "for-løkke", "if", "tellere"],
    moduleIds: [5],
  },
  {
    id: "10-regneregler",
    grade: "10",
    goal: "bruke regneregler og generalisere sammenhenger algebraisk",
    fit: "God støtte",
    activity: "Test en påstand for mange tall, beskriv mønsteret og bruk SymPy til å vise den algebraiske sammenhengen.",
    tools: ["løkker", "SymPy", "variabler", "uttrykk"],
    moduleIds: [1, 3, 4],
  },
  {
    id: "10-kvadratsetninger",
    grade: "10",
    goal: "utforske kvadratsetningene geometrisk og algebraisk og bruke kvadratsetningene som regnestrategier",
    fit: "Direkte",
    activity: "Tegn arealdelene med Turtle og sammenlign den geometriske modellen med et uttrykk som utvides i SymPy.",
    tools: ["Turtle", "areal", "SymPy", "farger"],
    moduleIds: [4, 7],
  },
  {
    id: "10-ligningssett",
    grade: "10",
    goal: "lage, løse og forklare ligningssett knyttet til praktiske situasjoner",
    fit: "God støtte",
    activity: "Modeller en praktisk situasjon med to funksjoner, finn skjæringspunktet grafisk og kontroller med SymPy.",
    tools: ["funksjoner", "Matplotlib", "SymPy", "grafer"],
    moduleIds: [4, 6, 9],
  },
  {
    id: "10-funksjonstyper",
    grade: "10",
    goal: "utforske og sammenligne egenskaper ved lineære funksjoner, eksponentialfunksjoner, brøkfunksjoner og andregradsfunksjoner ved å bruke digitale verktøy",
    fit: "Direkte",
    activity: "Tegn flere funksjonstyper i samme koordinatsystem og undersøk nullpunkter, vekst, asymptoter og parameterendringer.",
    tools: ["NumPy", "Matplotlib", "funksjoner", "grafer"],
    moduleIds: [4, 6, 9],
  },
  {
    id: "10-stigningstall",
    grade: "10",
    goal: "forklare begrepet endring per enhet og regne ut stigningstallet til lineære funksjoner",
    fit: "Direkte",
    activity: "Beregn endring i y delt på endring i x, tegn linjen og koble stigningstallet til den praktiske situasjonen.",
    tools: ["funksjoner", "tabeller", "Matplotlib", "variabler"],
    moduleIds: [1, 4, 9],
  },
  {
    id: "10-prosentvekst",
    grade: "10",
    goal: "utforske og forklare sammenhengen mellom konstant prosentvis endring, vekstfaktor og eksponentialfunksjoner",
    fit: "Direkte",
    activity: "Sammenlign prosentvis endring periode for periode med potensmodellen, og vis utviklingen som tabell og graf.",
    tools: ["vekstfaktor", "**", "løkker", "Matplotlib"],
    moduleIds: [1, 4, 6, 9],
  },
  {
    id: "10-okonomi-konsekvenser",
    grade: "10",
    goal: "hente ut og tolke relevant informasjon og reflektere over mulige konsekvenser ved kjøp og salg, renter på sparing, lån og kredittkjøp",
    fit: "Direkte",
    activity: "Lag sammenlignbare modeller for sparing, lån og kreditt. Vis total kostnad og undersøk virkningen av rente og tid.",
    tools: ["variabler", "vekstfaktor", "tabeller", "grafer"],
    moduleIds: [1, 6, 9],
  },
  {
    id: "10-okonomi-arbeid",
    grade: "10",
    goal: "planlegge, utføre og presentere et utforskende arbeid knyttet til personlig økonomi",
    fit: "Direkte",
    activity: "Formuler et økonomisk spørsmål, samle forutsetninger, programmer en modell og presenter funn og begrensninger.",
    tools: ["Pandas", "Matplotlib", "modeller", "f-tekst"],
    moduleIds: [1, 6, 9],
  },
  {
    id: "10-modellering",
    grade: "10",
    goal: "modellere situasjoner, presentere resultatene og vurdere hvor gyldige modellene er",
    fit: "Direkte",
    activity: "Gjør antakelser om til variabler, beregn eller simuler utviklingen, presenter resultatet og test modellens grenser.",
    tools: ["funksjoner", "tabeller", "grafer", "simulering"],
    moduleIds: [4, 5, 6, 9],
  },
  {
    id: "10-programmering",
    grade: "10",
    goal: "utforske matematiske egenskaper og sammenhenger ved å bruke programmering",
    fit: "Direkte",
    activity: "Still et matematisk spørsmål, lag kode som produserer eksempler, og bruk mønsteret til å formulere og begrunne en sammenheng.",
    tools: ["løkker", "funksjoner", "Turtle", "grafer"],
    moduleIds: [3, 4, 5, 7, 8, 9],
  },
  {
    id: "10-pythonkode",
    grade: "10",
    goal: "lese og forklare tekstbasert programkode i Python",
    fit: "Direkte",
    activity: "Følg variabelverdier linje for linje, forutsi resultatet, forklar matematikken og foreslå en begrunnet endring.",
    tools: ["variabler", "if/else", "løkker", "funksjoner"],
    moduleIds: [1, 2, 3, 4, 8, 9],
  },
];