export const learningOrder = [1, 2, 3, 4, 10, 5, 6, 9, 7, 8];
export const lessonSteps = ["Forstå", "Forutsi", "Prøv", "Forklar", "Oppgave"];
export const lessonMeta: Record<number, { before:string; goal:string; minutes:string; extra:string; tests:string[] }> = {
  1:{before:"Ingen programmering fra før",goal:"Forklar hvordan verdier lagres og brukes i et regnestykke.",minutes:"20–30 min",extra:"Lag et program som regner ut pris med både rabatt og frakt.",tests:["800 kr med 30 % rabatt → 560 kr", "500 kr med 20 % rabatt → 400 kr"]},
  2:{before:"Variabler og print",goal:"Forutsi hvilken gren programmet velger.",minutes:"20–30 min",extra:"Lag en regel som velger mellom tre billettpriser.",tests:["37 → oddetall", "0 og 18 → partall", "−3 → oddetall"]},
  3:{before:"Variabler, innrykk og print",goal:"Følg løkkevariabelen og forklar mønsteret.",minutes:"25–35 min",extra:"Lag en while-løkke som dobler et tall fram til det er minst 100.",tests:["3, 6, 9, 12, 15", "Endre til firegangen: 4, 8, 12, 16, 20"]},
  4:{before:"Variabler og regneuttrykk",goal:"Skill mellom å definere, kalle, returnere og skrive ut.",minutes:"25–35 min",extra:"Lag din egen arealfunksjon og bruk den med tre forskjellige mål.",tests:["f(6) → 16", "f(0) → −2", "f(−2) → −8"]},
  5:{before:"Vilkår, løkker og tellere",goal:"Forklar forskjellen på teoretisk sannsynlighet og målt andel.",minutes:"30–40 min",extra:"Undersøk en annen hendelse og sammenlign med sannsynligheten du regner ut.",tests:["Bare kast 1 og 2 skal øke telleren", "Andelen må være mellom 0 og 1", "Kjør flere ganger; svaret skal kunne variere"]},
  6:{before:"Prosent, potenser og variabler",goal:"Forklar modellens beregning og når antakelsene er rimelige.",minutes:"25–35 min",extra:"Lag en modell med både prosentvis vekst og et årlig innskudd.",tests:["1000 kr, 5 %, 3 år → omtrent 1157,63 kr", "0 år → startverdien", "0 % vekst → samme verdi"]},
  7:{before:"Løkker og vinkler",goal:"Tegn og forklar en regulær åttekant.",minutes:"30–40 min",extra:"Velg farge og tykkelse. Spill av figuren og eksporter SVG.",tests:["8 sider og 45° sving → lukket åttekant", "4 sider og 90° sving → kvadrat", "Dobbel lengde endrer ikke antallet sider"]},
  8:{before:"Variabler, vilkår og grunnleggende lister",goal:"Utforsk og begrunn innstillingene i et ferdig Snake-bibliotek.",minutes:"30–45 min",extra:"Gå videre til Pygame for å skrive bevegelse og kollisjon selv.",tests:["Prøv begge veggreglene", "Sammenlign to hastigheter", "Forklar hvilke deler som er skjult i spill-biblioteket"]},
  9:{before:"Funksjoner og grunnleggende lister",goal:"Tegn en graf og kontroller verdier, akser og nullpunkt.",minutes:"30–45 min",extra:"Bruk den komplette grafmalen for å velge utsnitt, tallsteg og akseforhold.",tests:["f(0) = 6", "f(2) = 0", "f(4) = −6", "Grafen må krysse x-aksen ved 2"]},
  10:{before:"Variabler og løkker",goal:"Les data, regn med tallverdier og hold dager og temperaturer sammen.",minutes:"3 × 20 min",extra:"Håndter tomme rader og flere like varme dager.",tests:["Eksempelfilen: gjennomsnitt 13,0", "Finn alle dager med høyeste temperatur", "Prøv en ny liste og en fil med tom rad"]},
};
